/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package Model;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the class Car
 * 
 * @author Acceleo 3 Example - UML to Java generator
 * @generated
 */
public class Car {
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public Car() {
		super();
	}
	
	
	/* StateMachine for Car */
	void Main_init(void) {
	    // Initialization code for state machine
	}
	
	void Main_step(void) {
	    // State machine step function
	}
	
	
}
