/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package Model;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the class Car
 * 
 * @author Acceleo 3 Example - UML to Java generator
 * @generated
 */
public class Car {
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public Car() {
		super();
	}
	
	
	
	/* ============================================
	 * State Machines belonging to Car
	 * ============================================ */
	
	StateMachine: MainTop
	
	    
	    
	    
	    
	        
	        
	    R Region1
	        
	        
	        
	        
	        
	        
	    
	    
	    
	    
	R Region0
	
	    
	        
	        
	        
	        
	        
	    
	R Region1
	StateMachine: SubTop
	
	    
	    
	    
	    
	R Region0
	
	    
	    
	R Region1
	
}
