/* File generated by Đức's ClasHStamP */

import type { long, Boolean, String } from "@all_notations/java_sample00/stdtype/stdtype";
import { BaseClass } from "@all_notations/java_sample00/abstracts/BaseClass";
import { BaseStmTop } from "@all_notations/java_sample00/abstracts/BaseStmTop";

export class StateMachine {
    public static readonly STATE_UNDEF: long = 0;

    public Enterable(
        nThisState: long
    ): Boolean {
        // BOOL isThisLCA = IS_IN( pHdStateMachine->nLCAState, nThisState );
        const isThisLCA: boolean = StateMachine.isIn(this.nLCAState, nThisState);

        // if( !isThisLCA || pHdStateMachine->nLCAState == STATE_UNDEF ){ return TRUE; }
        if (!isThisLCA || this.nLCAState === StateMachine.STATE_UNDEF) {
            return true;
        }
        return false;
    } /* StateMachine.Enterable */

    public Exitable(
        nThisState: long
    ): Boolean {
        // BOOL isThisLCA = IS_IN( pHdStateMachine->nSourceState, nThisState )
        //                   && IS_IN( pHdStateMachine->nTargetState, nThisState );
        const isThisLCA: boolean =
            StateMachine.isIn(this.nSourceState, nThisState) &&
            StateMachine.isIn(this.nTargetState, nThisState);

        // if( !isThisLCA || pHdStateMachine->bIsExternTrans ){
        //     pHdStateMachine->bIsExternTrans &= !isThisLCA;
        //     return TRUE;
        // } else {
        //     pHdStateMachine->nLCAState = nThisState;
        // }
        // return FALSE;
        if (!isThisLCA || this.bIsExternTrans === true) {
            this.bIsExternTrans = this.bIsExternTrans && !isThisLCA;
            return true;
        } else {
            this.nLCAState = nThisState;
        }
        return false;
    } /* StateMachine.Exitable */

    public DefaultEntryAction(
        pObj: BaseClass,
        pMsg: String
    ): void {
        // pHdStateMachine->lastEnteredState = pHdStateMachine->nCurrentState;
        this.lastEnteredState = this.nCurrentState;

        // pHdStateMachine->nDepth++;   // nDepth was not in Java skeleton, so omitted.
        console.log("Enter " + pMsg.substring(pMsg.lastIndexOf('\t')));
    } /* StateMachine.DefaultEntryAction */

    public DefaultExitAction(
        pObj: BaseClass,
        pMsg: String
    ): void {
        console.log("Exit" + pMsg.substring(pMsg.lastIndexOf('\t')));
    } /* StateMachine.DefaultExitAction */

    public DefaultDoingAction(
        pObj: BaseClass,
        pMsg: String
    ): void {
        // Intentionally empty
    } /* StateMachine.DefaultDoingAction */

    public IsIn(
        nState: long
    ): Boolean {
        const targetState: long = nState;
        return StateMachine.isIn(this.nCurrentState, targetState);
    } /* StateMachine.IsIn */

    public Req(
        entryPt: long
    ): void {
        this.nPseudostate = entryPt;
        // NOTE: C version forgot to return a bool; Java version is void, so this matches better.
    } /* StateMachine.Req */

    private static isIn(
        leaf: long,
        composite: long
    ): boolean {
        return composite >= leaf && (composite & leaf) !== 0;
    } /* StateMachine.isIn */

    public constructor() {
        this.pParentStm = null;
        this.nCurrentState = StateMachine.STATE_UNDEF;
        this.nLCAState = StateMachine.STATE_UNDEF;
        this.nTargetState = StateMachine.STATE_UNDEF;
        this.nSourceState = StateMachine.STATE_UNDEF;
        this.nPseudostate = StateMachine.STATE_UNDEF;
        this.bIsExternTrans = false;
        this.bHandled = false;
        this.wasHandled = false;
        this.lastEnteredState = StateMachine.STATE_UNDEF;
        this.pMain = null;
    }

    public pParentStm: StateMachine | null;
    public nCurrentState: long;
    public nLCAState: long;
    public nTargetState: long;
    public nSourceState: long;
    public nPseudostate: long;
    public bIsExternTrans: Boolean;
    public bHandled: Boolean;
    public wasHandled: Boolean;
    public lastEnteredState: long;
    public pMain: BaseStmTop | null;
}
