/* File generated by Đức's ClasHStamP */
package all_notations.java_sample00.interfaces;

import java.io.*;
import java.util.*;

public  interface Interface2
{
    public void methodWithParams(
        String parm1,
        Integer parm2
    );
}
