/* File generated by Đức's ClasHStamP */
package all_notations.java_sample00.interfaces;

import java.io.*;
import java.util.*;

public  interface Interface1
{
    public void finalMethod(
    );                                                                                  
}
