/* File generated by Đức's ClasHStamP */
import type { Integer, long, Boolean, String } from "#all_notations/java_sample00/stdtype/stdtype";

export class EventParams
{
    constructor(
    ){
    }                                                                                           
}
