/* File generated by Đức's ClasHStamP */
import type { Integer, long, Boolean, String } from "#all_notations/java_sample00/stdtype/stdtype";
import { BaseClass } from "#all_notations/java_sample00/abstracts/BaseClass";

export class StateMachine
{
    public static readonly STATE_UNDEF: long = 0;               
    public Enterable(
        nThisState: long
    ): Boolean {
		return false;
    } /* StateMachine.Enterable */

    public Exitable(
        nThisState: long
    ): Boolean {
		return false;
    } /* StateMachine.Exitable */
    public DefaultEntryAction(
        pObj: BaseClass,
        pMsg: String
    ): void {
    } /* StateMachine.DefaultEntryAction */

    public DefaultExitAction(
        pObj: BaseClass,
        pMsg: String
    ): void {
    } /* StateMachine.DefaultExitAction */

    public DefaultDoingAction(
        pObj: BaseClass,
        pMsg: String
    ): void {
    } /* StateMachine.DefaultDoingAction */

    public IsIn(
        nState: long
    ): Boolean {
		return false;
    } /* StateMachine.IsIn */

    public Req(
        entryPt: long
    ): void {
    } /* StateMachine.Req */

    private staticisIn(
        leaf: long,
        composite: long
    ): Boolean {
		return false;
    } /* StateMachine.isIn */
    constructor(
    ){
        this.pParentStm = undefined;
        this.nCurrentState = StateMachine.STATE_UNDEF;
        this.nLCAState = StateMachine.STATE_UNDEF;
        this.nTargetState = StateMachine.STATE_UNDEF;
        this.nSourceState = StateMachine.STATE_UNDEF;
        this.nPseudostate = StateMachine.STATE_UNDEF;
        this.bIsExternTrans = false;
        this.bHandled = false;
        this.wasHandled = false;
        this.lastEnteredState = StateMachine.STATE_UNDEF;
        this.pMain = undefined;
    }                                                                                           
    public pParentStm: StateMachine | undefined;                              
    public nCurrentState: long;                                 
    public nLCAState: long;                                     
    public nTargetState: long;                                  
    public nSourceState: long;                                  
    public nPseudostate: long;                                  
    public bIsExternTrans: Boolean;                             
    public bHandled: Boolean;                                   
    public wasHandled: Boolean;                                 
    public lastEnteredState: long;                              
    public pMain: Object | undefined;                              
}
