/* File generated by Đức's ClasHStamP */
#define __ContextImpl_INTERNAL__
#include "CommonInclude.h"
#include "ContextImpl.h"
#include "Composition.h"                                        
#include "Aggregration.h"                                       
#include "EventParams.h"                                        
#include "BaseClass.h"                                          
const TCHAR* ContextImplEvent_toString( ContextImpl_EVENT value ){
    switch( value ){
    case ContextImpl_E0: return _T( "E0" );
    case ContextImpl_E1: return _T( "E1" );
    case ContextImpl_E2: return _T( "E2" );
    case ContextImpl_E3: return _T( "E3" );
    case ContextImpl_E4: return _T( "E4" );
    case ContextImpl_E5: return _T( "E5" );
    default: return _T( "ContextImpl_UNKNOWN" );
    }
}
static BOOL MainStmTop_Reset( ContextImpl* pContextImpl, MainStmTop* pUsm, STM_RESET* pResetParams );
static void MainStmTop_Prepare( MainStmTop* pUsm, HdStateMachine* pParent );
static BOOL MainStmTop_EventProc( ContextImpl* pContextImpl, MainStmTop* pUsm, ContextImpl_EVENT nEventId, void* pEventParams );
static BOOL MainStmTop_StateDefaultTrans( ContextImpl* pContextImpl, MainStmTop* pUsm );
BOOL ContextImpl_Start( ContextImpl* pContextImpl ){
    MainStmTop_Prepare( &pContextImpl->mainStm, NULL );
    BOOL bResult = MainStmTop_Reset( pContextImpl, &pContextImpl->mainStm, NULL );
    bResult |= MainStmTop_StateDefaultTrans( pContextImpl, &pContextImpl->mainStm );
    return bResult;
}
BOOL ContextImpl_EventProc( ContextImpl* pContextImpl, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = MainStmTop_EventProc( pContextImpl, &pContextImpl->mainStm, nEventId, pEventParams );
    bResult |= MainStmTop_StateDefaultTrans( pContextImpl, &pContextImpl->mainStm );
    return bResult;
}
/** @protected @memberof ContextImpl */
static void ContextImpl_protectedMethod(
    BaseClass* pBaseClass
){
} /* ContextImpl_protectedMethod */

void ContextImpl_checkE1Params(
    EventParams e
){
} /* ContextImpl_checkE1Params */

Context* ContextImpl_Copy( ContextImpl* pContextImpl, const ContextImpl* pSource ){
    Context_Copy( ( Context* )pContextImpl, ( Context* )pSource );
    return ( BaseClass* )pContextImpl;
}
const BaseClassVtbl gContextImplVtbl = {
    .pprotectedMethod            = ContextImpl_protectedMethod,
};
static void SubStmTop_SubStm_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, SubStmTop_SubStm ) ){
if( !( ( SubStmTop* )pStm->pMain )->lastEnteredStateRecovering && pStm->nTargetState == SubStmTop_SubStm ){
    pStm->nPseudostate = SubStmTop_SubStmInit;
}
if ( ( ( SubStmTop* )pStm->pMain )->lastEnteredStateRecovering ) {
    pStm->nPseudostate = pStm->lastEnteredState;
}
    }
}
static BOOL SubStmTop_SubStm_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = SubStmTop_SubStm;
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return pStm->bHandled;
}
static void SubStmTop_SubStm_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, SubStmTop_SubStm ) ){ 
    }
}
static void SubStmTop_S101_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, SubStmTop_S101 ) ){
        SubStmTop_SubStm_Entry( pContextImpl, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/SubStm/	" );
    }
}
static BOOL SubStmTop_S101_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = SubStmTop_S101;
        HdStateMachine_DefaultDoingAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/SubStm/	" );
        switch( nEventId ){
        case ContextImpl_E5:{
    SubStmHsm_BgnTrans( pContextImpl, pStm, SubStmTop_S102 );
    SubStmHsm_EndTrans( pContextImpl, pStm );
    bResult |= TRUE;
        } break;
        default: break;
        }
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return SubStmTop_SubStm_EventProc( pContextImpl, pStm, nEventId, pEventParams );
}
static void SubStmTop_S101_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, SubStmTop_S101 ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/SubStm/	" );
        SubStmTop_SubStm_Exit( pContextImpl, pStm );
    }
}
static void SubStmTop_S102_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, SubStmTop_S102 ) ){
        SubStmTop_SubStm_Entry( pContextImpl, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/SubStm/	" );
    }
}
static BOOL SubStmTop_S102_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = SubStmTop_S102;
        HdStateMachine_DefaultDoingAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/SubStm/	" );
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return SubStmTop_SubStm_EventProc( pContextImpl, pStm, nEventId, pEventParams );
}
static void SubStmTop_S102_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, SubStmTop_S102 ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/SubStm/	" );
        SubStmTop_SubStm_Exit( pContextImpl, pStm );
    }
}
static void SubStmHsm_BgnTrans( ContextImpl *pContextImpl, HdStateMachine* pStm, uint64_t targetState ){
    pStm->nTargetState = targetState;
    pStm->nPseudostate = targetState;
    switch( pStm->nCurrentState ){
    case SubStmTop_SubStm:      SubStmTop_SubStm_Exit( pContextImpl, pStm ); break;
    case SubStmTop_S101:        SubStmTop_S101_Exit( pContextImpl, pStm ); break;
    case SubStmTop_S102:        SubStmTop_S102_Exit( pContextImpl, pStm ); break;
    default: break;
    }
}
static BOOL SubStmHsm_Reset( ContextImpl* pContextImpl, HdStateMachine* pStm, STM_RESET* pResetParams ) {
    if( pResetParams != NULL && pResetParams->entryPt != STATE_UNDEF ){
        HdStateMachine_Req( pStm, pResetParams->entryPt );
        return FALSE;
    }
    pStm->nPseudostate = SubStmTop_SubStm;
    pStm->bIsExternTrans = TRUE;
    pStm->nDepth = ( pResetParams != NULL ? pResetParams->nDepth + 1 : 0 );
    SubStmHsm_BgnTrans( pContextImpl, pStm, pStm->nPseudostate );
    SubStmHsm_EndTrans( pContextImpl, pStm );
    HdStateMachine_IsIn( pStm, STATE_UNDEF );    // used for testcases generation
    return TRUE;
}
static BOOL SubStmHsm_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->nLCAState = STATE_UNDEF;
    pStm->bHandled = FALSE;
    pStm->wasHandled = FALSE;
    switch( pStm->nCurrentState ){
    case SubStmTop_SubStm:                      bResult |= SubStmTop_SubStm_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    case SubStmTop_S101:                        bResult |= SubStmTop_S101_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    case SubStmTop_S102:                        bResult |= SubStmTop_S102_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    default: break;
    }
    return bResult;
}
static BOOL SubStmHsm_Abort( ContextImpl* pContextImpl, HdStateMachine* pStm ) {
    pStm->nSourceState = SubStmTop_SubStm;
    SubStmHsm_BgnTrans( pContextImpl, pStm, STATE_UNDEF );
    SubStmHsm_EndTrans( pContextImpl, pStm );
    HdStateMachine_IsIn( pStm, STATE_UNDEF );    // used for testcases generation
    return TRUE;
}
static void SubStmHsm_EndTrans( ContextImpl *pContextImpl, HdStateMachine* pStm ){
    pStm->nCurrentState = pStm->nTargetState;
    pStm->bIsExternTrans = FALSE;
    switch( pStm->nCurrentState ){
    case SubStmTop_SubStm:      SubStmTop_SubStm_Entry( pContextImpl, pStm ); break;
    case SubStmTop_S101:        SubStmTop_S101_Entry( pContextImpl, pStm ); break;
    case SubStmTop_S102:        SubStmTop_S102_Entry( pContextImpl, pStm ); break;
    default: break;
    }
}
static BOOL SubStmHsm_StateDefaultTrans( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    BOOL bResult = FALSE;
    pStm->nSourceState = pStm->nCurrentState;
    pStm->nLCAState = STATE_UNDEF;
if ( pStm->nPseudostate == SubStmTop_SubStmInit  ) {
    SubStmHsm_BgnTrans( pContextImpl, pStm, SubStmTop_S101 );
    SubStmHsm_EndTrans( pContextImpl, pStm );
    bResult |= TRUE;
} else if ( pStm->nCurrentState == SubStmTop_S102 && pStm->nPseudostate == SubStmTop_S102  ) {
    SubStmHsm_BgnTrans( pContextImpl, pStm, SubStmTop_SubStm );
    HdStateMachine_Req( ( ( SubStmTop* )pStm->pMain )->pParentStm, SubStmTop_Exit1 );    SubStmHsm_EndTrans( pContextImpl, pStm );
    bResult |= TRUE;
}else if( pStm->nCurrentState != pStm->nPseudostate ){
    SubStmHsm_BgnTrans( pContextImpl, pStm, pStm->nPseudostate );
    SubStmHsm_EndTrans( pContextImpl, pStm );
    bResult = TRUE;
}else{
}
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    ( ( SubStmTop* )pStm->pMain )->lastEnteredStateRecovering = FALSE;
    return bResult;
}
static void MainStmTop_S8Rgn1_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainStmTop_S8Rgn1 ) ){
if( !( ( MainStmTop* )pStm->pMain )->lastEnteredStateRecovering && pStm->nTargetState == MainStmTop_S8Rgn1 ){
    pStm->nPseudostate = MainStmTop_S82Init;
}
if ( ( ( MainStmTop* )pStm->pMain )->lastEnteredStateRecovering ) {
    pStm->nPseudostate = pStm->lastEnteredState;
}
    }
}
static BOOL MainStmTop_S8Rgn1_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainStmTop_S8Rgn1;
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return pStm->bHandled;
}
static void MainStmTop_S8Rgn1_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainStmTop_S8Rgn1 ) ){ 
    }
}
static void MainStmTop_S821_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainStmTop_S821 ) ){
        MainStmTop_S8Rgn1_Entry( pContextImpl, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
    }
}
static BOOL MainStmTop_S821_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainStmTop_S821;
        HdStateMachine_DefaultDoingAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        switch( nEventId ){
        case ContextImpl_E2:{
    if (HdStateMachine_IsIn( &( ( MainStmTop* )pStm->pMain )->MainStmHsm, MainStmTop_S812 )) {
        MainStmHsm_Reset( pContextImpl, &( ( MainStmTop* )pStm->pMain )->MainStmHsm, &( STM_RESET ){ .entryPt = MainStmTop_S811 } );
    }
        } break;
        default: break;
        }
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainStmTop_S8Rgn1_EventProc( pContextImpl, pStm, nEventId, pEventParams );
}
static void MainStmTop_S821_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainStmTop_S821 ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        MainStmTop_S8Rgn1_Exit( pContextImpl, pStm );
    }
}
static void MainStmTop_S822_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainStmTop_S822 ) ){
        MainStmTop_S8Rgn1_Entry( pContextImpl, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
    }
}
static BOOL MainStmTop_S822_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainStmTop_S822;
        HdStateMachine_DefaultDoingAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainStmTop_S8Rgn1_EventProc( pContextImpl, pStm, nEventId, pEventParams );
}
static void MainStmTop_S822_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainStmTop_S822 ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        MainStmTop_S8Rgn1_Exit( pContextImpl, pStm );
    }
}
static void S8Rgn1Hsm_BgnTrans( ContextImpl *pContextImpl, HdStateMachine* pStm, uint64_t targetState ){
    pStm->nTargetState = targetState;
    pStm->nPseudostate = targetState;
    switch( pStm->nCurrentState ){
    case MainStmTop_S8Rgn1:     MainStmTop_S8Rgn1_Exit( pContextImpl, pStm ); break;
    case MainStmTop_S821:       MainStmTop_S821_Exit( pContextImpl, pStm ); break;
    case MainStmTop_S822:       MainStmTop_S822_Exit( pContextImpl, pStm ); break;
    default: break;
    }
}
static BOOL S8Rgn1Hsm_Reset( ContextImpl* pContextImpl, HdStateMachine* pStm, STM_RESET* pResetParams ) {
    if( pResetParams != NULL && pResetParams->entryPt != STATE_UNDEF ){
        HdStateMachine_Req( pStm, pResetParams->entryPt );
        return FALSE;
    }
    pStm->nPseudostate = MainStmTop_S8Rgn1;
    pStm->bIsExternTrans = TRUE;
    pStm->nDepth = ( pResetParams != NULL ? pResetParams->nDepth + 1 : 0 );
    S8Rgn1Hsm_BgnTrans( pContextImpl, pStm, pStm->nPseudostate );
    S8Rgn1Hsm_EndTrans( pContextImpl, pStm );
    HdStateMachine_IsIn( pStm, STATE_UNDEF );    // used for testcases generation
    return TRUE;
}
static BOOL S8Rgn1Hsm_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->nLCAState = STATE_UNDEF;
    pStm->bHandled = FALSE;
    pStm->wasHandled = FALSE;
    switch( pStm->nCurrentState ){
    case MainStmTop_S8Rgn1:                     bResult |= MainStmTop_S8Rgn1_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    case MainStmTop_S821:                       bResult |= MainStmTop_S821_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    case MainStmTop_S822:                       bResult |= MainStmTop_S822_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    default: break;
    }
    return bResult;
}
static BOOL S8Rgn1Hsm_Abort( ContextImpl* pContextImpl, HdStateMachine* pStm ) {
    pStm->nSourceState = MainStmTop_S8Rgn1;
    S8Rgn1Hsm_BgnTrans( pContextImpl, pStm, STATE_UNDEF );
    S8Rgn1Hsm_EndTrans( pContextImpl, pStm );
    HdStateMachine_IsIn( pStm, STATE_UNDEF );    // used for testcases generation
    return TRUE;
}
static void S8Rgn1Hsm_EndTrans( ContextImpl *pContextImpl, HdStateMachine* pStm ){
    pStm->nCurrentState = pStm->nTargetState;
    pStm->bIsExternTrans = FALSE;
    switch( pStm->nCurrentState ){
    case MainStmTop_S8Rgn1:     MainStmTop_S8Rgn1_Entry( pContextImpl, pStm ); break;
    case MainStmTop_S821:       MainStmTop_S821_Entry( pContextImpl, pStm ); break;
    case MainStmTop_S822:       MainStmTop_S822_Entry( pContextImpl, pStm ); break;
    default: break;
    }
}
static BOOL S8Rgn1Hsm_StateDefaultTrans( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    BOOL bResult = FALSE;
    pStm->nSourceState = pStm->nCurrentState;
    pStm->nLCAState = STATE_UNDEF;
if ( pStm->nPseudostate == MainStmTop_S82Init  ) {
    S8Rgn1Hsm_BgnTrans( pContextImpl, pStm, MainStmTop_S821 );
    S8Rgn1Hsm_EndTrans( pContextImpl, pStm );
    bResult |= TRUE;
}else if( pStm->nCurrentState != pStm->nPseudostate ){
    S8Rgn1Hsm_BgnTrans( pContextImpl, pStm, pStm->nPseudostate );
    S8Rgn1Hsm_EndTrans( pContextImpl, pStm );
    bResult = TRUE;
}else{
}
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    ( ( MainStmTop* )pStm->pMain )->lastEnteredStateRecovering = FALSE;
    return bResult;
}
static void MainStmTop_S71Rgn1_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainStmTop_S71Rgn1 ) ){
if( !( ( MainStmTop* )pStm->pMain )->lastEnteredStateRecovering && pStm->nTargetState == MainStmTop_S71Rgn1 ){
    pStm->nPseudostate = MainStmTop_S712Init;
}
if ( ( ( MainStmTop* )pStm->pMain )->lastEnteredStateRecovering ) {
    pStm->nPseudostate = pStm->lastEnteredState;
}
    }
}
static BOOL MainStmTop_S71Rgn1_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainStmTop_S71Rgn1;
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return pStm->bHandled;
}
static void MainStmTop_S71Rgn1_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainStmTop_S71Rgn1 ) ){ 
    }
}
static void MainStmTop_S7121_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainStmTop_S7121 ) ){
        MainStmTop_S71Rgn1_Entry( pContextImpl, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
    }
}
static BOOL MainStmTop_S7121_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainStmTop_S7121;
        HdStateMachine_DefaultDoingAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        switch( nEventId ){
        case ContextImpl_E5:{
    S71Rgn1Hsm_BgnTrans( pContextImpl, pStm, MainStmTop_S7122 );
    S71Rgn1Hsm_EndTrans( pContextImpl, pStm );
    bResult |= TRUE;
        } break;
        default: break;
        }
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainStmTop_S71Rgn1_EventProc( pContextImpl, pStm, nEventId, pEventParams );
}
static void MainStmTop_S7121_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainStmTop_S7121 ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        MainStmTop_S71Rgn1_Exit( pContextImpl, pStm );
    }
}
static void MainStmTop_S7122_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainStmTop_S7122 ) ){
        MainStmTop_S71Rgn1_Entry( pContextImpl, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
    }
}
static BOOL MainStmTop_S7122_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainStmTop_S7122;
        HdStateMachine_DefaultDoingAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainStmTop_S71Rgn1_EventProc( pContextImpl, pStm, nEventId, pEventParams );
}
static void MainStmTop_S7122_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainStmTop_S7122 ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        MainStmTop_S71Rgn1_Exit( pContextImpl, pStm );
    }
}
static void S71Rgn1Hsm_BgnTrans( ContextImpl *pContextImpl, HdStateMachine* pStm, uint64_t targetState ){
    pStm->nTargetState = targetState;
    pStm->nPseudostate = targetState;
    switch( pStm->nCurrentState ){
    case MainStmTop_S71Rgn1:    MainStmTop_S71Rgn1_Exit( pContextImpl, pStm ); break;
    case MainStmTop_S7121:      MainStmTop_S7121_Exit( pContextImpl, pStm ); break;
    case MainStmTop_S7122:      MainStmTop_S7122_Exit( pContextImpl, pStm ); break;
    default: break;
    }
}
static BOOL S71Rgn1Hsm_Reset( ContextImpl* pContextImpl, HdStateMachine* pStm, STM_RESET* pResetParams ) {
    if( pResetParams != NULL && pResetParams->entryPt != STATE_UNDEF ){
        HdStateMachine_Req( pStm, pResetParams->entryPt );
        return FALSE;
    }
    pStm->nPseudostate = MainStmTop_S71Rgn1;
    pStm->bIsExternTrans = TRUE;
    pStm->nDepth = ( pResetParams != NULL ? pResetParams->nDepth + 1 : 0 );
    S71Rgn1Hsm_BgnTrans( pContextImpl, pStm, pStm->nPseudostate );
    S71Rgn1Hsm_EndTrans( pContextImpl, pStm );
    HdStateMachine_IsIn( pStm, STATE_UNDEF );    // used for testcases generation
    return TRUE;
}
static BOOL S71Rgn1Hsm_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->nLCAState = STATE_UNDEF;
    pStm->bHandled = FALSE;
    pStm->wasHandled = FALSE;
    switch( pStm->nCurrentState ){
    case MainStmTop_S71Rgn1:                    bResult |= MainStmTop_S71Rgn1_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    case MainStmTop_S7121:                      bResult |= MainStmTop_S7121_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    case MainStmTop_S7122:                      bResult |= MainStmTop_S7122_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    default: break;
    }
    return bResult;
}
static BOOL S71Rgn1Hsm_Abort( ContextImpl* pContextImpl, HdStateMachine* pStm ) {
    pStm->nSourceState = MainStmTop_S71Rgn1;
    S71Rgn1Hsm_BgnTrans( pContextImpl, pStm, STATE_UNDEF );
    S71Rgn1Hsm_EndTrans( pContextImpl, pStm );
    HdStateMachine_IsIn( pStm, STATE_UNDEF );    // used for testcases generation
    return TRUE;
}
static void S71Rgn1Hsm_EndTrans( ContextImpl *pContextImpl, HdStateMachine* pStm ){
    pStm->nCurrentState = pStm->nTargetState;
    pStm->bIsExternTrans = FALSE;
    switch( pStm->nCurrentState ){
    case MainStmTop_S71Rgn1:    MainStmTop_S71Rgn1_Entry( pContextImpl, pStm ); break;
    case MainStmTop_S7121:      MainStmTop_S7121_Entry( pContextImpl, pStm ); break;
    case MainStmTop_S7122:      MainStmTop_S7122_Entry( pContextImpl, pStm ); break;
    default: break;
    }
}
static BOOL S71Rgn1Hsm_StateDefaultTrans( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    BOOL bResult = FALSE;
    pStm->nSourceState = pStm->nCurrentState;
    pStm->nLCAState = STATE_UNDEF;
if ( pStm->nPseudostate == MainStmTop_S712Init  ) {
    S71Rgn1Hsm_BgnTrans( pContextImpl, pStm, MainStmTop_S7121 );
    S71Rgn1Hsm_EndTrans( pContextImpl, pStm );
    bResult |= TRUE;
}else if( pStm->nCurrentState != pStm->nPseudostate ){
    S71Rgn1Hsm_BgnTrans( pContextImpl, pStm, pStm->nPseudostate );
    S71Rgn1Hsm_EndTrans( pContextImpl, pStm );
    bResult = TRUE;
}else{
}
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    ( ( MainStmTop* )pStm->pMain )->lastEnteredStateRecovering = FALSE;
    return bResult;
}
static void MainStmTop_MainStm_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainStmTop_MainStm ) ){
if( !( ( MainStmTop* )pStm->pMain )->lastEnteredStateRecovering && pStm->nTargetState == MainStmTop_MainStm ){
    pStm->nPseudostate = MainStmTop_MainStmInit;
}
if ( ( ( MainStmTop* )pStm->pMain )->lastEnteredStateRecovering ) {
    pStm->nPseudostate = pStm->lastEnteredState;
}
    }
}
static BOOL MainStmTop_MainStm_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainStmTop_MainStm;
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return pStm->bHandled;
}
static void MainStmTop_MainStm_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainStmTop_MainStm ) ){ 
    }
}
static void MainStmTop_S1_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainStmTop_S1 ) ){
        MainStmTop_MainStm_Entry( pContextImpl, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
    }
}
static BOOL MainStmTop_S1_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainStmTop_S1;
        HdStateMachine_DefaultDoingAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        switch( nEventId ){
        case ContextImpl_E1:{
    MainStmHsm_BgnTrans( pContextImpl, pStm, MainStmTop_S2 );
    printf("Hello, World!");
    MainStmHsm_EndTrans( pContextImpl, pStm );
    bResult |= TRUE;
        } break;
        case ContextImpl_E2:{
    if (pContextImpl.internalAttribute == 0) {
        MainStmHsm_BgnTrans( pContextImpl, pStm, MainStmTop_S2 );
        MainStmHsm_EndTrans( pContextImpl, pStm );
        bResult |= TRUE;
    } else {
        if (pContextImpl.internalAttribute == 1) {
            MainStmHsm_BgnTrans( pContextImpl, pStm, MainStmTop_S6 );
            SubStmTop_Reset( pContextImpl, &( ( MainStmTop* )pStm->pMain )->S6Hsm, &( STM_RESET ){ .lastEnteredStateRecovering = ( ( MainStmTop* )pStm->pMain )->lastEnteredStateRecovering, .entryPt = SubStmTop_Entry1 } );
            MainStmHsm_EndTrans( pContextImpl, pStm );
            bResult |= TRUE;
        } else {
            MainStmHsm_BgnTrans( pContextImpl, pStm, MainStmTop_S7 );
            MainStmHsm_EndTrans( pContextImpl, pStm );
            bResult |= TRUE;
        }
    }
        } break;
        default: break;
        }
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainStmTop_MainStm_EventProc( pContextImpl, pStm, nEventId, pEventParams );
}
static void MainStmTop_S1_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainStmTop_S1 ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        MainStmTop_MainStm_Exit( pContextImpl, pStm );
    }
}
static void MainStmTop_S2_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainStmTop_S2 ) ){
        MainStmTop_MainStm_Entry( pContextImpl, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
if( !( ( MainStmTop* )pStm->pMain )->lastEnteredStateRecovering && pStm->nTargetState == MainStmTop_S2 ){
    pStm->nPseudostate = MainStmTop_S2Init;
}
    }
}
static BOOL MainStmTop_S2_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainStmTop_S2;
        HdStateMachine_DefaultDoingAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        switch( nEventId ){
        case ContextImpl_E4:{
    MainStmHsm_BgnTrans( pContextImpl, pStm, MainStmTop_S6 );
    MainStmHsm_EndTrans( pContextImpl, pStm );
    bResult |= TRUE;
        } break;
        case ContextImpl_E2:{
    MainStmHsm_BgnTrans( pContextImpl, pStm, MainStmTop_S3 );
    MainStmHsm_EndTrans( pContextImpl, pStm );
    bResult |= TRUE;
        } break;
        default: break;
        }
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainStmTop_MainStm_EventProc( pContextImpl, pStm, nEventId, pEventParams );
}
static void MainStmTop_S2_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainStmTop_S2 ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        MainStmTop_MainStm_Exit( pContextImpl, pStm );
    }
}
static void MainStmTop_S21_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainStmTop_S21 ) ){
        MainStmTop_S2_Entry( pContextImpl, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
( ( MainStmTop* )pStm->pMain )->S2ShallowHist = MainStmTop_S21;
    }
}
static BOOL MainStmTop_S21_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainStmTop_S21;
        HdStateMachine_DefaultDoingAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        switch( nEventId ){
        case ContextImpl_E2:{
    MainStmHsm_BgnTrans( pContextImpl, pStm, MainStmTop_S22 );
    MainStmHsm_EndTrans( pContextImpl, pStm );
    bResult |= TRUE;
        } break;
        case ContextImpl_E1:{
    MainStmHsm_BgnTrans( pContextImpl, pStm, MainStmTop_S3 );
    MainStmHsm_EndTrans( pContextImpl, pStm );
    bResult |= TRUE;
        } break;
        default: break;
        }
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainStmTop_S2_EventProc( pContextImpl, pStm, nEventId, pEventParams );
}
static void MainStmTop_S21_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainStmTop_S21 ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        MainStmTop_S2_Exit( pContextImpl, pStm );
    }
}
static void MainStmTop_S22_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainStmTop_S22 ) ){
        MainStmTop_S2_Entry( pContextImpl, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
( ( MainStmTop* )pStm->pMain )->S2ShallowHist = MainStmTop_S22;
    }
}
static BOOL MainStmTop_S22_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainStmTop_S22;
        HdStateMachine_DefaultDoingAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        switch( nEventId ){
        case ContextImpl_E0:{
    ( ( MainStmTop* )pStm->pMain )->S2ShallowHist = STATE_UNDEF;
    MainStmHsm_BgnTrans( pContextImpl, pStm, MainStmTop_MainStm );
    MainStmHsm_EndTrans( pContextImpl, pStm );
    bResult |= TRUE;
        } break;
        default: break;
        }
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainStmTop_S2_EventProc( pContextImpl, pStm, nEventId, pEventParams );
}
static void MainStmTop_S22_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainStmTop_S22 ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        MainStmTop_S2_Exit( pContextImpl, pStm );
    }
}
static void MainStmTop_S8_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainStmTop_S8 ) ){
        MainStmTop_MainStm_Entry( pContextImpl, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
if( !( ( MainStmTop* )pStm->pMain )->lastEnteredStateRecovering && pStm->nTargetState == MainStmTop_S8 ){
    pStm->nPseudostate = MainStmTop_S81Init;
}
S8Rgn1Hsm_Reset( pContextImpl, &( ( MainStmTop* )pStm->pMain )->S8Rgn1Hsm, &( STM_RESET ){ .nDepth = pStm->nDepth } );
    }
}
static BOOL MainStmTop_S8_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->bHandled |= S8Rgn1Hsm_EventProc( pContextImpl, &( ( MainStmTop* )pStm->pMain )->S8Rgn1Hsm, nEventId, pEventParams );
    if( !pStm->bHandled ){
        pStm->nSourceState = MainStmTop_S8;
        HdStateMachine_DefaultDoingAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        switch( nEventId ){
        case ContextImpl_E3:{
    if( ( ( MainStmTop* )pStm->pMain )->S2ShallowHist != STATE_UNDEF ){
        MainStmHsm_BgnTrans( pContextImpl, pStm, ( ( MainStmTop* )pStm->pMain )->S2ShallowHist );
        MainStmHsm_EndTrans( pContextImpl, pStm );
        bResult |= TRUE;
    }else{
        MainStmHsm_BgnTrans( pContextImpl, pStm, MainStmTop_MainStm );
        MainStmHsm_EndTrans( pContextImpl, pStm );
        bResult |= TRUE;
    }
        } break;
        case ContextImpl_E5:{
    MainStmHsm_BgnTrans( pContextImpl, pStm, MainStmTop_S7 );
    MainStmHsm_EndTrans( pContextImpl, pStm );
    bResult |= TRUE;
        } break;
        default: break;
        }
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainStmTop_MainStm_EventProc( pContextImpl, pStm, nEventId, pEventParams );
}
static void MainStmTop_S8_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainStmTop_S8 ) ){ 
S8Rgn1Hsm_Abort( pContextImpl, &( ( MainStmTop* )pStm->pMain )->S8Rgn1Hsm );
        HdStateMachine_DefaultExitAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        MainStmTop_MainStm_Exit( pContextImpl, pStm );
    }
}
static void MainStmTop_S811_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainStmTop_S811 ) ){
        MainStmTop_S8_Entry( pContextImpl, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
    }
}
static BOOL MainStmTop_S811_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainStmTop_S811;
        HdStateMachine_DefaultDoingAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainStmTop_S8_EventProc( pContextImpl, pStm, nEventId, pEventParams );
}
static void MainStmTop_S811_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainStmTop_S811 ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        MainStmTop_S8_Exit( pContextImpl, pStm );
    }
}
static void MainStmTop_S812_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainStmTop_S812 ) ){
        MainStmTop_S8_Entry( pContextImpl, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
    }
}
static BOOL MainStmTop_S812_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainStmTop_S812;
        HdStateMachine_DefaultDoingAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainStmTop_S8_EventProc( pContextImpl, pStm, nEventId, pEventParams );
}
static void MainStmTop_S812_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainStmTop_S812 ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        MainStmTop_S8_Exit( pContextImpl, pStm );
    }
}
static void MainStmTop_S7_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainStmTop_S7 ) ){
        MainStmTop_MainStm_Entry( pContextImpl, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
if( !( ( MainStmTop* )pStm->pMain )->lastEnteredStateRecovering && pStm->nTargetState == MainStmTop_S7 ){
    pStm->nPseudostate = MainStmTop_S7Init;
}
    }
}
static BOOL MainStmTop_S7_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainStmTop_S7;
        HdStateMachine_DefaultDoingAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        switch( nEventId ){
        case ContextImpl_E2:{
    MainStmHsm_BgnTrans( pContextImpl, pStm, MainStmTop_S72 );
    MainStmHsm_EndTrans( pContextImpl, pStm );
    bResult |= TRUE;
        } break;
        case ContextImpl_E1:{
    MainStmHsm_BgnTrans( pContextImpl, pStm, MainStmTop_S71 );
    MainStmHsm_EndTrans( pContextImpl, pStm );
    bResult |= TRUE;
        } break;
        default: break;
        }
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainStmTop_MainStm_EventProc( pContextImpl, pStm, nEventId, pEventParams );
}
static void MainStmTop_S7_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainStmTop_S7 ) ){ 
( ( MainStmTop* )pStm->pMain )->S7DeepHist = pStm->lastEnteredState;        HdStateMachine_DefaultExitAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        MainStmTop_MainStm_Exit( pContextImpl, pStm );
    }
}
static void MainStmTop_S71_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainStmTop_S71 ) ){
        MainStmTop_S7_Entry( pContextImpl, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
if( !( ( MainStmTop* )pStm->pMain )->lastEnteredStateRecovering && pStm->nTargetState == MainStmTop_S71 ){
    pStm->nPseudostate = MainStmTop_S711Init;
}
S71Rgn1Hsm_Reset( pContextImpl, &( ( MainStmTop* )pStm->pMain )->S71Rgn1Hsm, &( STM_RESET ){ .nDepth = pStm->nDepth } );
    }
}
static BOOL MainStmTop_S71_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->bHandled |= S71Rgn1Hsm_EventProc( pContextImpl, &( ( MainStmTop* )pStm->pMain )->S71Rgn1Hsm, nEventId, pEventParams );
    if( !pStm->bHandled ){
        pStm->nSourceState = MainStmTop_S71;
        HdStateMachine_DefaultDoingAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainStmTop_S7_EventProc( pContextImpl, pStm, nEventId, pEventParams );
}
static void MainStmTop_S71_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainStmTop_S71 ) ){ 
S71Rgn1Hsm_Abort( pContextImpl, &( ( MainStmTop* )pStm->pMain )->S71Rgn1Hsm );
        HdStateMachine_DefaultExitAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        MainStmTop_S7_Exit( pContextImpl, pStm );
    }
}
static void MainStmTop_S7111_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainStmTop_S7111 ) ){
        MainStmTop_S71_Entry( pContextImpl, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
    }
}
static BOOL MainStmTop_S7111_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainStmTop_S7111;
        HdStateMachine_DefaultDoingAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        switch( nEventId ){
        case ContextImpl_E0:{
    MainStmHsm_BgnTrans( pContextImpl, pStm, MainStmTop_S7112 );
    MainStmHsm_EndTrans( pContextImpl, pStm );
    bResult |= TRUE;
        } break;
        default: break;
        }
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainStmTop_S71_EventProc( pContextImpl, pStm, nEventId, pEventParams );
}
static void MainStmTop_S7111_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainStmTop_S7111 ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        MainStmTop_S71_Exit( pContextImpl, pStm );
    }
}
static void MainStmTop_S7112_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainStmTop_S7112 ) ){
        MainStmTop_S71_Entry( pContextImpl, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
    }
}
static BOOL MainStmTop_S7112_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainStmTop_S7112;
        HdStateMachine_DefaultDoingAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainStmTop_S71_EventProc( pContextImpl, pStm, nEventId, pEventParams );
}
static void MainStmTop_S7112_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainStmTop_S7112 ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        MainStmTop_S71_Exit( pContextImpl, pStm );
    }
}
static void MainStmTop_S72_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainStmTop_S72 ) ){
        MainStmTop_S7_Entry( pContextImpl, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
    }
}
static BOOL MainStmTop_S72_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainStmTop_S72;
        HdStateMachine_DefaultDoingAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainStmTop_S7_EventProc( pContextImpl, pStm, nEventId, pEventParams );
}
static void MainStmTop_S72_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainStmTop_S72 ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        MainStmTop_S7_Exit( pContextImpl, pStm );
    }
}
static void MainStmTop_S6_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainStmTop_S6 ) ){
        MainStmTop_MainStm_Entry( pContextImpl, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
SubStmTop_Reset( pContextImpl, &( ( MainStmTop* )pStm->pMain )->S6Hsm, &( STM_RESET ){ .nDepth = pStm->nDepth } );
    }
}
static BOOL MainStmTop_S6_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->bHandled |= SubStmTop_EventProc( pContextImpl, &( ( MainStmTop* )pStm->pMain )->S6Hsm, nEventId, pEventParams );
    if( !pStm->bHandled ){
        pStm->nSourceState = MainStmTop_S6;
        HdStateMachine_DefaultDoingAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainStmTop_MainStm_EventProc( pContextImpl, pStm, nEventId, pEventParams );
}
static void MainStmTop_S6_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainStmTop_S6 ) ){ 
SubStmTop_Abort( pContextImpl, &( ( MainStmTop* )pStm->pMain )->S6Hsm );
        HdStateMachine_DefaultExitAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        MainStmTop_MainStm_Exit( pContextImpl, pStm );
    }
}
static void MainStmTop_S3_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainStmTop_S3 ) ){
        MainStmTop_MainStm_Entry( pContextImpl, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
    }
}
static BOOL MainStmTop_S3_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainStmTop_S3;
        HdStateMachine_DefaultDoingAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        switch( nEventId ){
        case ContextImpl_E0:{
    MainStmHsm_BgnTrans( pContextImpl, pStm, MainStmTop_S6 );
    MainStmHsm_EndTrans( pContextImpl, pStm );
    bResult |= TRUE;
        } break;
        default: break;
        }
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainStmTop_MainStm_EventProc( pContextImpl, pStm, nEventId, pEventParams );
}
static void MainStmTop_S3_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainStmTop_S3 ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        MainStmTop_MainStm_Exit( pContextImpl, pStm );
    }
}
static void MainStmTop_S9_Entry( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainStmTop_S9 ) ){
        MainStmTop_MainStm_Entry( pContextImpl, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
SubStmTop_Reset( pContextImpl, &( ( MainStmTop* )pStm->pMain )->S9Hsm, &( STM_RESET ){ .nDepth = pStm->nDepth } );
    }
}
static BOOL MainStmTop_S9_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->bHandled |= SubStmTop_EventProc( pContextImpl, &( ( MainStmTop* )pStm->pMain )->S9Hsm, nEventId, pEventParams );
    if( !pStm->bHandled ){
        pStm->nSourceState = MainStmTop_S9;
        HdStateMachine_DefaultDoingAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainStmTop_MainStm_EventProc( pContextImpl, pStm, nEventId, pEventParams );
}
static void MainStmTop_S9_Exit( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainStmTop_S9 ) ){ 
SubStmTop_Abort( pContextImpl, &( ( MainStmTop* )pStm->pMain )->S9Hsm );
        HdStateMachine_DefaultExitAction( pStm, pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	" );
        MainStmTop_MainStm_Exit( pContextImpl, pStm );
    }
}
static void MainStmHsm_BgnTrans( ContextImpl *pContextImpl, HdStateMachine* pStm, uint64_t targetState ){
    pStm->nTargetState = targetState;
    pStm->nPseudostate = targetState;
    switch( pStm->nCurrentState ){
    case MainStmTop_MainStm:    MainStmTop_MainStm_Exit( pContextImpl, pStm ); break;
    case MainStmTop_S1:         MainStmTop_S1_Exit( pContextImpl, pStm ); break;
    case MainStmTop_S21:        MainStmTop_S21_Exit( pContextImpl, pStm ); break;
    case MainStmTop_S22:        MainStmTop_S22_Exit( pContextImpl, pStm ); break;
    case MainStmTop_S2:         MainStmTop_S2_Exit( pContextImpl, pStm ); break;
    case MainStmTop_S811:       MainStmTop_S811_Exit( pContextImpl, pStm ); break;
    case MainStmTop_S812:       MainStmTop_S812_Exit( pContextImpl, pStm ); break;
    case MainStmTop_S8:         MainStmTop_S8_Exit( pContextImpl, pStm ); break;
    case MainStmTop_S7111:      MainStmTop_S7111_Exit( pContextImpl, pStm ); break;
    case MainStmTop_S7112:      MainStmTop_S7112_Exit( pContextImpl, pStm ); break;
    case MainStmTop_S71:        MainStmTop_S71_Exit( pContextImpl, pStm ); break;
    case MainStmTop_S72:        MainStmTop_S72_Exit( pContextImpl, pStm ); break;
    case MainStmTop_S7:         MainStmTop_S7_Exit( pContextImpl, pStm ); break;
    case MainStmTop_S6:         MainStmTop_S6_Exit( pContextImpl, pStm ); break;
    case MainStmTop_S3:         MainStmTop_S3_Exit( pContextImpl, pStm ); break;
    case MainStmTop_S9:         MainStmTop_S9_Exit( pContextImpl, pStm ); break;
    default: break;
    }
}
static BOOL MainStmHsm_Reset( ContextImpl* pContextImpl, HdStateMachine* pStm, STM_RESET* pResetParams ) {
    if( pResetParams != NULL && pResetParams->entryPt != STATE_UNDEF ){
        HdStateMachine_Req( pStm, pResetParams->entryPt );
        return FALSE;
    }
    pStm->nPseudostate = MainStmTop_MainStm;
    pStm->bIsExternTrans = TRUE;
    pStm->nDepth = ( pResetParams != NULL ? pResetParams->nDepth + 1 : 0 );
    MainStmHsm_BgnTrans( pContextImpl, pStm, pStm->nPseudostate );
    MainStmHsm_EndTrans( pContextImpl, pStm );
    HdStateMachine_IsIn( pStm, STATE_UNDEF );    // used for testcases generation
    return TRUE;
}
static BOOL MainStmHsm_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->nLCAState = STATE_UNDEF;
    pStm->bHandled = FALSE;
    pStm->wasHandled = FALSE;
    switch( pStm->nCurrentState ){
    case MainStmTop_MainStm:                    bResult |= MainStmTop_MainStm_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    case MainStmTop_S1:                         bResult |= MainStmTop_S1_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    case MainStmTop_S21:                        bResult |= MainStmTop_S21_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    case MainStmTop_S22:                        bResult |= MainStmTop_S22_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    case MainStmTop_S2:                         bResult |= MainStmTop_S2_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    case MainStmTop_S811:                       bResult |= MainStmTop_S811_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    case MainStmTop_S812:                       bResult |= MainStmTop_S812_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    case MainStmTop_S8:                         bResult |= MainStmTop_S8_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    case MainStmTop_S7111:                      bResult |= MainStmTop_S7111_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    case MainStmTop_S7112:                      bResult |= MainStmTop_S7112_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    case MainStmTop_S71:                        bResult |= MainStmTop_S71_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    case MainStmTop_S72:                        bResult |= MainStmTop_S72_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    case MainStmTop_S7:                         bResult |= MainStmTop_S7_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    case MainStmTop_S6:                         bResult |= MainStmTop_S6_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    case MainStmTop_S3:                         bResult |= MainStmTop_S3_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    case MainStmTop_S9:                         bResult |= MainStmTop_S9_EventProc( pContextImpl, pStm, nEventId, pEventParams ); break;
    default: break;
    }
    return bResult;
}
static BOOL MainStmHsm_Abort( ContextImpl* pContextImpl, HdStateMachine* pStm ) {
    pStm->nSourceState = MainStmTop_MainStm;
    MainStmHsm_BgnTrans( pContextImpl, pStm, STATE_UNDEF );
    MainStmHsm_EndTrans( pContextImpl, pStm );
    HdStateMachine_IsIn( pStm, STATE_UNDEF );    // used for testcases generation
    return TRUE;
}
static void MainStmHsm_EndTrans( ContextImpl *pContextImpl, HdStateMachine* pStm ){
    pStm->nCurrentState = pStm->nTargetState;
    pStm->bIsExternTrans = FALSE;
    switch( pStm->nCurrentState ){
    case MainStmTop_MainStm:    MainStmTop_MainStm_Entry( pContextImpl, pStm ); break;
    case MainStmTop_S1:         MainStmTop_S1_Entry( pContextImpl, pStm ); break;
    case MainStmTop_S21:        MainStmTop_S21_Entry( pContextImpl, pStm ); break;
    case MainStmTop_S22:        MainStmTop_S22_Entry( pContextImpl, pStm ); break;
    case MainStmTop_S2:         MainStmTop_S2_Entry( pContextImpl, pStm ); break;
    case MainStmTop_S811:       MainStmTop_S811_Entry( pContextImpl, pStm ); break;
    case MainStmTop_S812:       MainStmTop_S812_Entry( pContextImpl, pStm ); break;
    case MainStmTop_S8:         MainStmTop_S8_Entry( pContextImpl, pStm ); break;
    case MainStmTop_S7111:      MainStmTop_S7111_Entry( pContextImpl, pStm ); break;
    case MainStmTop_S7112:      MainStmTop_S7112_Entry( pContextImpl, pStm ); break;
    case MainStmTop_S71:        MainStmTop_S71_Entry( pContextImpl, pStm ); break;
    case MainStmTop_S72:        MainStmTop_S72_Entry( pContextImpl, pStm ); break;
    case MainStmTop_S7:         MainStmTop_S7_Entry( pContextImpl, pStm ); break;
    case MainStmTop_S6:         MainStmTop_S6_Entry( pContextImpl, pStm ); break;
    case MainStmTop_S3:         MainStmTop_S3_Entry( pContextImpl, pStm ); break;
    case MainStmTop_S9:         MainStmTop_S9_Entry( pContextImpl, pStm ); break;
    default: break;
    }
}
static BOOL MainStmHsm_StateDefaultTrans( ContextImpl* pContextImpl, HdStateMachine* pStm ){
    BOOL bResult = FALSE;
    pStm->nSourceState = pStm->nCurrentState;
    pStm->nLCAState = STATE_UNDEF;
if ( pStm->nPseudostate == MainStmTop_MainStmInit  ) {
    MainStmHsm_BgnTrans( pContextImpl, pStm, MainStmTop_S1 );
    MainStmHsm_EndTrans( pContextImpl, pStm );
    bResult |= TRUE;
} else if ( pStm->nCurrentState == MainStmTop_S6 && pStm->nPseudostate == SubStmTop_Exit1  ) {
    MainStmHsm_BgnTrans( pContextImpl, pStm, MainStmTop_S9 );
    MainStmHsm_EndTrans( pContextImpl, pStm );
    bResult |= TRUE;
} else if ( pStm->nCurrentState == MainStmTop_S9 && pStm->nPseudostate == MainStmTop_S9 
 && SubStmTop_IsFinished( &( ( MainStmTop* )pStm->pMain )->S9Hsm ) ) {
    MainStmHsm_BgnTrans( pContextImpl, pStm, MainStmTop_S812 );
    S8Rgn1Hsm_Reset( pContextImpl, &( ( MainStmTop* )pStm->pMain )->S8Rgn1Hsm, &( STM_RESET ){ .entryPt = MainStmTop_S821 } );
    MainStmHsm_EndTrans( pContextImpl, pStm );
    bResult |= TRUE;
} else if ( pStm->nPseudostate == MainStmTop_S2Init  ) {
    MainStmHsm_BgnTrans( pContextImpl, pStm, MainStmTop_S21 );
    MainStmHsm_EndTrans( pContextImpl, pStm );
    bResult |= TRUE;
} else if ( pStm->nPseudostate == MainStmTop_S81Init  ) {
    MainStmHsm_BgnTrans( pContextImpl, pStm, MainStmTop_S811 );
    MainStmHsm_EndTrans( pContextImpl, pStm );
    bResult |= TRUE;
} else if ( pStm->nPseudostate == MainStmTop_S711Init  ) {
    MainStmHsm_BgnTrans( pContextImpl, pStm, MainStmTop_S7111 );
    MainStmHsm_EndTrans( pContextImpl, pStm );
    bResult |= TRUE;
} else if ( pStm->nPseudostate == MainStmTop_S7Init  ) {
    if( ( ( MainStmTop* )pStm->pMain )->S7DeepHist != STATE_UNDEF ){
        MainStmHsm_BgnTrans( pContextImpl, pStm, ( ( MainStmTop* )pStm->pMain )->S7DeepHist );
        ( ( MainStmTop* )pStm->pMain )->lastEnteredStateRecovering = TRUE;
        MainStmHsm_EndTrans( pContextImpl, pStm );
        bResult |= TRUE;
    }else{
        MainStmHsm_BgnTrans( pContextImpl, pStm, MainStmTop_S71 );
        MainStmHsm_EndTrans( pContextImpl, pStm );
        bResult |= TRUE;
    }
}else if( pStm->nCurrentState != pStm->nPseudostate ){
    MainStmHsm_BgnTrans( pContextImpl, pStm, pStm->nPseudostate );
    MainStmHsm_EndTrans( pContextImpl, pStm );
    bResult = TRUE;
}else{
}
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    ( ( MainStmTop* )pStm->pMain )->lastEnteredStateRecovering = FALSE;
    return bResult;
}

/**
 * Implementation for Statemachine: SubStmTop
 */
const TCHAR* SubStmTop_State_toString( SubStmTop* pUsm, HdStateMachine* pHsm, uint64_t nState ){
    TCHAR* sState;
    if( pHsm == &pUsm->SubStmHsm ){
        switch( nState ){
        case SubStmTop_S101                     : sState = "S101"; break;
        case SubStmTop_SubStmInit               : sState = "SubStmInit"; break;
        case SubStmTop_S102                     : sState = "S102"; break;
        case SubStmTop_Entry1                   : sState = "Entry1"; break;
        case SubStmTop_Exit1                    : sState = "Exit1"; break;
        case SubStmTop_SubStm                   : sState = "SubStm"; break;
        default                                 : sState = "SubStm_OutOfRange"; break;
        }
    }else static void SubStmTop_BgnTrans( ContextImpl *pContextImpl, HdStateMachine* pStm, uint64_t targetState );
static void SubStmTop_EndTrans( ContextImpl *pContextImpl, HdStateMachine* pStm );
static BOOL SubStmTop_Abort( ContextImpl* pContextImpl, HdStateMachine* pStm );
static BOOL SubStmTop_Reset( ContextImpl* pContextImpl, HdStateMachine* pStm, STM_RESET* pResetParams );
static BOOL SubStmTop_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams );
{ 
        sState = "UnknownState";
    }
    return sState;
}
static BOOL SubStmTop_EventProc( ContextImpl* pContextImpl, SubStmTop* pUsm, ContextImpl_EVENT nEventId, void* pEventParams ){
    return SubStmHsm_EventProc( pContextImpl, &pUsm->SubStmHsm, nEventId, pEventParams );
}
static BOOL SubStmTop_StateDefaultTrans( ContextImpl* pContextImpl, SubStmTop* pUsm ){
    BOOL bResult;
    while( TRUE ){
        bResult = FALSE;
        bResult |= SubStmHsm_StateDefaultTrans( pContextImpl, &pUsm->SubStmHsm );
        if( bResult == FALSE ){
            break;
        }
    }
    return bResult;
}
static BOOL SubStmTop_Reset( ContextImpl* pContextImpl, SubStmTop* pUsm, STM_RESET* pResetParams ){
    pUsm->lastEnteredStateRecovering = ( pResetParams != NULL ? pResetParams->lastEnteredStateRecovering : FALSE );
    SubStmHsm_Abort( pContextImpl, &pUsm->SubStmHsm );
    return SubStmHsm_Reset( pContextImpl, &pUsm->SubStmHsm, pResetParams );
}
static BOOL SubStmTop_Abort( ContextImpl* pContextImpl, SubStmTop* pUsm ){
    return SubStmHsm_Abort( pContextImpl, &pUsm->SubStmHsm );
}
static BOOL SubStmTop_IsFinished( SubStmTop* pUsm ){
    return pUsm->SubStmHsm.nPseudostate == SubStmTop_SubStm;
}

static void SubStmTop_Prepare( SubStmTop* pUsm, HdStateMachine* pParent ){
    pUsm->pParentStm = pParent;
    pUsm->SubStmHsm.pMain = pUsm;
}

/**
 * Implementation for Statemachine: MainStmTop
 */
const TCHAR* MainStmTop_State_toString( MainStmTop* pUsm, HdStateMachine* pHsm, uint64_t nState ){
    TCHAR* sState;
    if( pHsm == &pUsm->S8Rgn1Hsm ){
        switch( nState ){
        case MainStmTop_S821                    : sState = "S821"; break;
        case MainStmTop_S82Init                 : sState = "S82Init"; break;
        case MainStmTop_S822                    : sState = "S822"; break;
        case MainStmTop_S8Rgn1                  : sState = "S8Rgn1"; break;
        default                                 : sState = "S8Rgn1_OutOfRange"; break;
        }
    }else if( pHsm == &pUsm->S71Rgn1Hsm ){
        switch( nState ){
        case MainStmTop_S7121                   : sState = "S7121"; break;
        case MainStmTop_S7122                   : sState = "S7122"; break;
        case MainStmTop_S712Init                : sState = "S712Init"; break;
        case MainStmTop_S71Rgn1                 : sState = "S71Rgn1"; break;
        default                                 : sState = "S71Rgn1_OutOfRange"; break;
        }
    }else if( pHsm == &pUsm->MainStmHsm ){
        switch( nState ){
        case MainStmTop_S1                      : sState = "S1"; break;
        case MainStmTop_MainStmInit             : sState = "MainStmInit"; break;
        case MainStmTop_S21                     : sState = "S21"; break;
        case MainStmTop_S22                     : sState = "S22"; break;
        case MainStmTop_S2Init                  : sState = "S2Init"; break;
        case MainStmTop_S2                      : sState = "S2"; break;
        case MainStmTop_S811                    : sState = "S811"; break;
        case MainStmTop_S81Init                 : sState = "S81Init"; break;
        case MainStmTop_S812                    : sState = "S812"; break;
        case MainStmTop_S8                      : sState = "S8"; break;
        case MainStmTop_S7111                   : sState = "S7111"; break;
        case MainStmTop_S7112                   : sState = "S7112"; break;
        case MainStmTop_S711Init                : sState = "S711Init"; break;
        case MainStmTop_S71                     : sState = "S71"; break;
        case MainStmTop_S7Init                  : sState = "S7Init"; break;
        case MainStmTop_S72                     : sState = "S72"; break;
        case MainStmTop_S7                      : sState = "S7"; break;
        case MainStmTop_S6                      : sState = "S6"; break;
        case MainStmTop_S3                      : sState = "S3"; break;
        case MainStmTop_S9                      : sState = "S9"; break;
        case MainStmTop_MainStm                 : sState = "MainStm"; break;
        default                                 : sState = "MainStm_OutOfRange"; break;
        }
    }else static void MainStmTop_BgnTrans( ContextImpl *pContextImpl, HdStateMachine* pStm, uint64_t targetState );
static void MainStmTop_EndTrans( ContextImpl *pContextImpl, HdStateMachine* pStm );
static BOOL MainStmTop_Abort( ContextImpl* pContextImpl, HdStateMachine* pStm );
static BOOL MainStmTop_Reset( ContextImpl* pContextImpl, HdStateMachine* pStm, STM_RESET* pResetParams );
static BOOL MainStmTop_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams );
static void S8Rgn1Hsm_BgnTrans( ContextImpl *pContextImpl, HdStateMachine* pStm, uint64_t targetState );
static void S8Rgn1Hsm_EndTrans( ContextImpl *pContextImpl, HdStateMachine* pStm );
static BOOL S8Rgn1Hsm_Abort( ContextImpl* pContextImpl, HdStateMachine* pStm );
static BOOL S8Rgn1Hsm_Reset( ContextImpl* pContextImpl, HdStateMachine* pStm, STM_RESET* pResetParams );
static BOOL S8Rgn1Hsm_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams );
static void S71Rgn1Hsm_BgnTrans( ContextImpl *pContextImpl, HdStateMachine* pStm, uint64_t targetState );
static void S71Rgn1Hsm_EndTrans( ContextImpl *pContextImpl, HdStateMachine* pStm );
static BOOL S71Rgn1Hsm_Abort( ContextImpl* pContextImpl, HdStateMachine* pStm );
static BOOL S71Rgn1Hsm_Reset( ContextImpl* pContextImpl, HdStateMachine* pStm, STM_RESET* pResetParams );
static BOOL S71Rgn1Hsm_EventProc( ContextImpl* pContextImpl, HdStateMachine* pStm, ContextImpl_EVENT nEventId, void* pEventParams );
{ 
        sState = "UnknownState";
    }
    return sState;
}
static BOOL MainStmTop_EventProc( ContextImpl* pContextImpl, MainStmTop* pUsm, ContextImpl_EVENT nEventId, void* pEventParams ){
    return MainStmHsm_EventProc( pContextImpl, &pUsm->MainStmHsm, nEventId, pEventParams );
}
static BOOL MainStmTop_StateDefaultTrans( ContextImpl* pContextImpl, MainStmTop* pUsm ){
    BOOL bResult;
    while( TRUE ){
        bResult = FALSE;
        bResult |= S8Rgn1Hsm_StateDefaultTrans( pContextImpl, &pUsm->S8Rgn1Hsm );
        bResult |= S71Rgn1Hsm_StateDefaultTrans( pContextImpl, &pUsm->S71Rgn1Hsm );
        bResult |= SubStmTop_StateDefaultTrans( pContextImpl, &pUsm->S6Hsm )
                    || SubStmTop_StateDefaultTrans( pContextImpl, &pUsm->S9Hsm )
                    || MainStmHsm_StateDefaultTrans( pContextImpl, &pUsm->MainStmHsm );
        if( bResult == FALSE ){
            break;
        }
    }
    return bResult;
}
static BOOL MainStmTop_Reset( ContextImpl* pContextImpl, MainStmTop* pUsm, STM_RESET* pResetParams ){
    pUsm->lastEnteredStateRecovering = ( pResetParams != NULL ? pResetParams->lastEnteredStateRecovering : FALSE );
    MainStmHsm_Abort( pContextImpl, &pUsm->MainStmHsm );
    return MainStmHsm_Reset( pContextImpl, &pUsm->MainStmHsm, pResetParams );
}
static BOOL MainStmTop_Abort( ContextImpl* pContextImpl, MainStmTop* pUsm ){
    return MainStmHsm_Abort( pContextImpl, &pUsm->MainStmHsm );
}
static BOOL MainStmTop_IsFinished( MainStmTop* pUsm ){
    return pUsm->MainStmHsm.nPseudostate == MainStmTop_MainStm;
}

static void MainStmTop_Prepare( MainStmTop* pUsm, HdStateMachine* pParent ){
    pUsm->pParentStm = pParent;
    pUsm->MainStmHsm.pMain = pUsm;
    pUsm->S8Rgn1Hsm.pMain = pUsm;
    pUsm->S71Rgn1Hsm.pMain = pUsm;
    SubStmTop_Prepare( &pUsm->S6Hsm, &pUsm->MainStmHsm );
    SubStmTop_Prepare( &pUsm->S9Hsm, &pUsm->MainStmHsm );
}
