/* File generated by Đức's ClasHStamP */
#define __Context_INTERNAL__
#include "CommonInclude.h"
#include "Context.h"
#include "Interface2.h"                                         
#include "Interface1.h"                                         
#include "UsedDependency.h"                                     
/** @private @static @memberof Context */
static Integer classOrStaticAttribute;                          
/** @private @static @memberof Context */
static Integer initializedStaticArray[ -1 ] = { 1, 2, 3 };      
/** @private @static @memberof Context */
static Integer finalConstantAttribute = 5;                      
void Context_classOrStaticMethod(

){
} /* Context_classOrStaticMethod */

/** @public @memberof Context */
static void Context_publicMethod(
    BaseClass* pBaseClass
){
} /* Context_publicMethod */

/** @private @memberof Context */
static void Context_privateLeafMethod(
    Context* pContext
){
} /* Context_privateLeafMethod */

/** @public @memberof Context */
void Context_methodWithParams(
    Context* pContext,
    String parm1,
    Integer parm2
){
} /* Context_methodWithParams */

/** @public @memberof Context */
UsedDependency Context_methodReturnsSomething(
    Context* pContext
){
} /* Context_methodReturnsSomething */

/** @public @memberof Context */
void Context_methodThrowsException(
    Context* pContext
){
} /* Context_methodThrowsException */

/** @public @memberof Context */
void Context_finalMethod(
    Context* pContext
){
} /* Context_finalMethod */

/** @protected @memberof Context */
static void Context_protectedMethod(
    BaseClass* pBaseClass
){
} /* Context_protectedMethod */

/** @protected @memberof Context */
static void Context_packageVisibleMethod(
    BaseClass* pBaseClass
){
} /* Context_packageVisibleMethod */

BaseClass* Context_Copy( Context* pContext, const Context* pSource ){
    BaseClass_Copy( ( BaseClass* )pContext, ( BaseClass* )pSource );
    pContext->publicAttribute = pSource->publicAttribute;
    pContext->privateAttribute = pSource->privateAttribute;
    pContext->internalAttribute = pSource->internalAttribute;
    pContext->isInitializedAttribute = pSource->isInitializedAttribute;
    pContext->readOnlyAttribute = pSource->readOnlyAttribute;
    memcpy( pContext->anAggregation, pSource->anAggregation, sizeof( pContext->anAggregation ) );
    memcpy( pContext->aProtectedComposition, pSource->aProtectedComposition, sizeof( pContext->aProtectedComposition ) );
    return ( BaseClass* )pContext;
}
const BaseClassVtbl gContextVtbl = {
    .ppublicMethod               = Context_publicMethod,
    .pprotectedMethod            = Context_protectedMethod,
    .ppackageVisibleMethod       = Context_packageVisibleMethod,
};
