/* File generated by Đức's ClasHStamP */
import type { Integer } from "#all_notations/java_sample00/stdtype/stdtype.js";
 /* class.name */
export class BaseClass
{ /* class.begin */
    public publicMethod( /* _ab_oper.name */ /* _ab_oper.begin */
    ): void {
 /* vptr_call.begin */ /* vptr_call.end */    } /* BaseClass.publicMethod */ /* _ab_oper.end */
 /* friend.ext1st */ /* friend.end */    protected protectedMethod( /* _ac_oper.name */ /* _ac_oper.begin */
    ): void {
 /* vptr_call.begin */ /* vptr_call.end */    } /* BaseClass.protectedMethod */ /* _ac_oper.end */

    protected packageVisibleMethod( /* _ac_oper.name */ /* _ac_oper.begin */
    ): void {
 /* vptr_call.begin */ /* vptr_call.end */    } /* BaseClass.packageVisibleMethod */ /* _ac_oper.end */

    constructor( /* constructor.name */ /* __s_attr.ext1st */
        _derivableAttribute: Integer /* constructor.begin */
    ){ /* constructor.ext1st */ /* __s_attr.begin */
        this.derivableAttribute = _derivableAttribute; /* constructor.end */
    }                                                                                           
 /* vptr_decl.name */ /* attr_group.name */ /* attr_group.ext1st */    derivableAttribute: Integer;                                 /* __s_attr.name */
 /* attr_group.end */} /* class.end */
