/* File generated by Đức's ClasHStamP */
import type { Integer, long, Boolean, String } from "#all_notations/java_sample00/stdtype/stdtype";

export class BaseClass
{
    public publicMethod(
    ): void {
    } /* BaseClass.publicMethod */
    protected protectedMethod(
    ): void {
    } /* BaseClass.protectedMethod */

    protected packageVisibleMethod(
    ): void {
    } /* BaseClass.packageVisibleMethod */

    constructor(
        _derivableAttribute: Integer
    ){
        this.derivableAttribute = _derivableAttribute;
    }                                                                                           
    derivableAttribute: Integer;                                
}
