/* File generated by Đức's ClasHStamP */
package design.model;

import java.io.*;
import java.util.*;

        public  class AFriend
        {
            public  AFriend(
                Integer _attribute3
            ){
                attribute3 = _attribute3;
            }                                                                                   
            Integer attribute3;                                 
        }
