/* File generated by Đức's ClasHStamP */
package design.model;

import java.io.*;
import java.util.*;

public  class Aggregration
{
    public  Aggregration(
        Integer _attribute2
    ){
        attribute2 = _attribute2;
    }                                                                                           
    private Integer attribute2;                                 
}
