/* File generated by Đức's ClasHStamP */
package design.model;

import java.io.*;
import java.util.*;
import design.model.*;
import design.base.*;
import design.abstracts.*;

public  class ContextImpl extends Context
{
    public static class onSpeedChangeParams extends EventParams{
        public Integer nKmPerHour;                              
    };
    public enum EventId {
        onAdasSwitch,
        onSpeedChange,
        Num
    };
    public boolean Start(){
        mainStm.Prepare( null, "mainStm" );
        boolean bResult = mainStm.Reset( this );
        bResult |= mainStm.StateDefaultTrans( this );
        return bResult;
    }
    public boolean EventProc( ContextImpl.EventId nEventId, EventParams pEventParams ){
        boolean bResult = mainStm.EventProc( this, nEventId, pEventParams );
        bResult |= mainStm.StateDefaultTrans( this );
        return bResult;
    }    protected void protectedMethod(
    ){
    } /* ContextImpl.protectedMethod */

    protected static void checkE1Params(
        EventParams e
    ){
    } /* ContextImpl.checkE1Params */
    public  ContextImpl(
        Integer _derivableAttribute,
        String _publicAttribute,
        Integer _privateAttribute,
        Integer _internalAttribute,
        Integer _readOnlyAttribute,
        ArrayList<Aggregration> _anAggregation,
        ArrayList<Composition> _aProtectedComposition
    ) {
        super( _derivableAttribute, _publicAttribute, _privateAttribute, _internalAttribute, _readOnlyAttribute, _anAggregation, _aProtectedComposition );
    mainStm = new MainStmTop();

    }                                                                                           
    MainStmTop mainStm;                                         
}
class _MainStmTop extends StateMachine {
        void MainStm_Entry( ContextImpl pContextImpl ){
            if( Enterable( MainStmTop.MainStm ) ){
        if( !( ( MainStmTop )pMain ).lastEnteredStateRecovering && nTargetState == MainStmTop.MainStm ){
            nPseudostate = MainStmTop.MainStmInit;
        }
        if ( ( ( MainStmTop )pMain ).lastEnteredStateRecovering ) {
            nPseudostate = lastEnteredState;
        }
            }
        }
        boolean MainStm_EventProc( ContextImpl pContextImpl, ContextImpl.EventId nEventId, EventParams pEventParams ){
            boolean bResult = false;
            if( !bHandled ){
                nSourceState = MainStmTop.MainStm;
            }
            bHandled |= bResult;
            wasHandled |= bResult;
            return bHandled;
        }
        void MainStm_Exit( ContextImpl pContextImpl ){
            if( Exitable( MainStmTop.MainStm ) ){ 
            }
        }
        void Off_Entry( ContextImpl pContextImpl ){
            if( Enterable( MainStmTop.Off ) ){
                MainStm_Entry( pContextImpl );
                DefaultEntryAction( pContextImpl, "MainStmTop	MainStm	239	100	221	61	30	30	1411	811	Off" );
            }
        }
        boolean Off_EventProc( ContextImpl pContextImpl, ContextImpl.EventId nEventId, EventParams pEventParams ){
            boolean bResult = false;
            if( !bHandled ){
                nSourceState = MainStmTop.Off;
                DefaultDoingAction( pContextImpl, "MainStmTop	MainStm	239	100	221	61	30	30	1411	811	Off" );
                switch( nEventId ){
                case ContextImpl.EventId.onAdasSwitch:{
            BgnTrans( pContextImpl, MainStmTop.On );
                DefaultTransAction("280	161	280	240");
            EndTrans( pContextImpl );
            bResult |= true;
                } break;
                default: break;
                }
            }
            bHandled |= bResult;
            wasHandled |= bResult;
            return MainStm_EventProc( pContextImpl, nEventId, pEventParams );
        }
        void Off_Exit( ContextImpl pContextImpl ){
            if( Exitable( MainStmTop.Off ) ){ 
                 DefaultExitAction( pContextImpl, "MainStmTop	MainStm	239	100	221	61	30	30	1411	811	Off" );
                MainStm_Exit( pContextImpl );
            }
        }
        void On_Entry( ContextImpl pContextImpl ){
            if( Enterable( MainStmTop.On ) ){
                MainStm_Entry( pContextImpl );
                DefaultEntryAction( pContextImpl, "MainStmTop	MainStm	99	240	521	228	30	30	1411	811	On" );
        if( !( ( MainStmTop )pMain ).lastEnteredStateRecovering && nTargetState == MainStmTop.On ){
            nPseudostate = MainStmTop.OnInit;
        }
            }
        }
        boolean On_EventProc( ContextImpl pContextImpl, ContextImpl.EventId nEventId, EventParams pEventParams ){
            boolean bResult = false;
            if( !bHandled ){
                nSourceState = MainStmTop.On;
                DefaultDoingAction( pContextImpl, "MainStmTop	MainStm	99	240	521	228	30	30	1411	811	On" );
                switch( nEventId ){
                case ContextImpl.EventId.onAdasSwitch:{
            BgnTrans( pContextImpl, MainStmTop.Off );
                DefaultTransAction("420	240	420	161");
            EndTrans( pContextImpl );
            bResult |= true;
                } break;
                default: break;
                }
            }
            bHandled |= bResult;
            wasHandled |= bResult;
            return MainStm_EventProc( pContextImpl, nEventId, pEventParams );
        }
        void On_Exit( ContextImpl pContextImpl ){
            if( Exitable( MainStmTop.On ) ){ 
                 DefaultExitAction( pContextImpl, "MainStmTop	MainStm	99	240	521	228	30	30	1411	811	On" );
                MainStm_Exit( pContextImpl );
            }
        }
        void Deactive_Entry( ContextImpl pContextImpl ){
            if( Enterable( MainStmTop.Deactive ) ){
                On_Entry( pContextImpl );
                DefaultEntryAction( pContextImpl, "MainStmTop	MainStm	138	340	141	61	30	30	1411	811	Deactive" );
            }
        }
        boolean Deactive_EventProc( ContextImpl pContextImpl, ContextImpl.EventId nEventId, EventParams pEventParams ){
            boolean bResult = false;
            if( !bHandled ){
                nSourceState = MainStmTop.Deactive;
                DefaultDoingAction( pContextImpl, "MainStmTop	MainStm	138	340	141	61	30	30	1411	811	Deactive" );
                switch( nEventId ){
                case ContextImpl.EventId.onSpeedChange:{
            design.model.ContextImpl.onSpeedChangeParams e = ( design.model.ContextImpl.onSpeedChangeParams )pEventParams; // need merge from "action" ★
            if (e.nKmPerHour > 10) {
                BgnTrans( pContextImpl, MainStmTop.Active );
                    DefaultTransAction("240	340	240	300	420	300	420	340");
                EndTrans( pContextImpl );
                bResult |= true;
            }
                } break;
                default: break;
                }
            }
            bHandled |= bResult;
            wasHandled |= bResult;
            return On_EventProc( pContextImpl, nEventId, pEventParams );
        }
        void Deactive_Exit( ContextImpl pContextImpl ){
            if( Exitable( MainStmTop.Deactive ) ){ 
                 DefaultExitAction( pContextImpl, "MainStmTop	MainStm	138	340	141	61	30	30	1411	811	Deactive" );
                On_Exit( pContextImpl );
            }
        }
        void Active_Entry( ContextImpl pContextImpl ){
            if( Enterable( MainStmTop.Active ) ){
                On_Entry( pContextImpl );
                DefaultEntryAction( pContextImpl, "MainStmTop	MainStm	378	340	141	61	30	30	1411	811	Active" );
            }
        }
        boolean Active_EventProc( ContextImpl pContextImpl, ContextImpl.EventId nEventId, EventParams pEventParams ){
            boolean bResult = false;
            if( !bHandled ){
                nSourceState = MainStmTop.Active;
                DefaultDoingAction( pContextImpl, "MainStmTop	MainStm	378	340	141	61	30	30	1411	811	Active" );
                switch( nEventId ){
                case ContextImpl.EventId.onSpeedChange:{
            design.model.ContextImpl.onSpeedChangeParams e = ( design.model.ContextImpl.onSpeedChangeParams )pEventParams; // need merge from "action" ★
            if (e.nKmPerHour <= 10) {
                BgnTrans( pContextImpl, MainStmTop.Deactive );
                    DefaultTransAction("420	401	420	440	240	440	240	401");
                EndTrans( pContextImpl );
                bResult |= true;
            }
                } break;
                default: break;
                }
            }
            bHandled |= bResult;
            wasHandled |= bResult;
            return On_EventProc( pContextImpl, nEventId, pEventParams );
        }
        void Active_Exit( ContextImpl pContextImpl ){
            if( Exitable( MainStmTop.Active ) ){ 
                 DefaultExitAction( pContextImpl, "MainStmTop	MainStm	378	340	141	61	30	30	1411	811	Active" );
                On_Exit( pContextImpl );
            }
        }
        void BgnTrans( ContextImpl pContextImpl, long targetState ){
            nTargetState = targetState;
            nPseudostate = targetState;
            if( nCurrentState == MainStmTop.MainStm ) { MainStm_Exit( pContextImpl ); }
            else if( nCurrentState == MainStmTop.Off ) { Off_Exit( pContextImpl ); }
            else if( nCurrentState == MainStmTop.Deactive ) { Deactive_Exit( pContextImpl ); }
            else if( nCurrentState == MainStmTop.Active ) { Active_Exit( pContextImpl ); }
            else if( nCurrentState == MainStmTop.On ) { On_Exit( pContextImpl ); }
            else {}
        }
        public boolean Reset(  ContextImpl pContextImpl ) {
            return Reset( pContextImpl, StateMachine.STATE_UNDEF, false );
        }
        public boolean Reset(  ContextImpl pContextImpl, boolean lastEnteredStateRecovering ) {
            return Reset( pContextImpl, StateMachine.STATE_UNDEF, lastEnteredStateRecovering );
        }
        public boolean Reset(  ContextImpl pContextImpl, long entryPt ) {
            return Reset( pContextImpl, entryPt, false );
        }
        public boolean Reset( ContextImpl pContextImpl, long entryPt, boolean lastEnteredStateRecovering ) {
            if( entryPt != StateMachine.STATE_UNDEF ){
                Req( entryPt );
                return false;
            }
            nPseudostate = MainStmTop.MainStm;
            bIsExternTrans = true;
            BgnTrans( pContextImpl, nPseudostate );
            EndTrans( pContextImpl );
            return true;
        }
        public boolean EventProc( ContextImpl pContextImpl, ContextImpl.EventId nEventId, EventParams pEventParams ){
            boolean bResult = false;
            nLCAState = StateMachine.STATE_UNDEF;
            bHandled = false;
            wasHandled = false;
            if( nCurrentState == MainStmTop.MainStm ) { MainStm_EventProc( pContextImpl, nEventId, pEventParams ); }
            else if( nCurrentState == MainStmTop.Off ) { Off_EventProc( pContextImpl, nEventId, pEventParams ); }
            else if( nCurrentState == MainStmTop.Deactive ) { Deactive_EventProc( pContextImpl, nEventId, pEventParams ); }
            else if( nCurrentState == MainStmTop.Active ) { Active_EventProc( pContextImpl, nEventId, pEventParams ); }
            else if( nCurrentState == MainStmTop.On ) { On_EventProc( pContextImpl, nEventId, pEventParams ); }
            else {}
            return bResult;
        }
        boolean Abort( ContextImpl pContextImpl ) {
            nSourceState = MainStmTop.MainStm;
            BgnTrans( pContextImpl, StateMachine.STATE_UNDEF );
            EndTrans( pContextImpl );
            return true;
        }
        void EndTrans( ContextImpl pContextImpl ){
            nCurrentState = nTargetState;
            bIsExternTrans = false;
            if( nCurrentState == MainStmTop.MainStm ) { MainStm_Entry( pContextImpl ); }
            else if( nCurrentState == MainStmTop.Off ) { Off_Entry( pContextImpl ); }
            else if( nCurrentState == MainStmTop.Deactive ) { Deactive_Entry( pContextImpl ); }
            else if( nCurrentState == MainStmTop.Active ) { Active_Entry( pContextImpl ); }
            else if( nCurrentState == MainStmTop.On ) { On_Entry( pContextImpl ); }
            else {}
        }
        boolean StateDefaultTrans( ContextImpl pContextImpl ){
            boolean bResult = false;
            nSourceState = nCurrentState;
            nLCAState = StateMachine.STATE_UNDEF;
        if ( nPseudostate == MainStmTop.MainStmInit  ) {
            BgnTrans( pContextImpl, MainStmTop.Off );
                DefaultTransAction("96	94	240	120");
            EndTrans( pContextImpl );
            bResult |= true;
        } else if ( nPseudostate == MainStmTop.OnInit  ) {
            BgnTrans( pContextImpl, MainStmTop.Deactive );
                DefaultTransAction("153	297	180	340");
            EndTrans( pContextImpl );
            bResult |= true;
            }else if( nCurrentState != nPseudostate ){
                BgnTrans( pContextImpl, nPseudostate );
                EndTrans( pContextImpl );
                bResult = true;
            }else{
            }
            bHandled |= bResult;
            wasHandled |= bResult;
            ( ( MainStmTop )pMain ).lastEnteredStateRecovering = false;
            return bResult;
        }
}
class MainStmTop extends BaseStmTop {
/* states' declaration */
        public static final long Off             = ( 1 <<  0 );
        public static final long MainStmInit     = ( 1 <<  1 );
        public static final long Deactive        = ( 1 <<  2 );
        public static final long Active          = ( 1 <<  3 );
        public static final long OnInit          = ( 1 <<  4 );
        public static final long On              = ( Deactive | Active | OnInit );
        public static final long MainStm         = ( Off | MainStmInit | On );
        _MainStmTop MainStmHsm = new _MainStmTop();             

        public boolean EventProc( ContextImpl pContextImpl, ContextImpl.EventId nEventId, EventParams pEventParams ){
            return MainStmHsm.EventProc( pContextImpl, nEventId, pEventParams );
        }
        public boolean StateDefaultTrans( ContextImpl pContextImpl ){
            boolean bResult;
            while( true ){
                bResult = false;
                bResult |= MainStmHsm.StateDefaultTrans( pContextImpl );
                if( bResult == false ){
                    break;
                }
            }
            return bResult;
        }
        public boolean Reset( ContextImpl pContextImpl ){
            return MainStmHsm.Reset( pContextImpl, StateMachine.STATE_UNDEF, false );
        }
        public boolean Reset( ContextImpl pContextImpl, long entryPt, boolean lastEnteredStateRecovering ){
            MainStmHsm.Abort( pContextImpl );
            return MainStmHsm.Reset( pContextImpl, entryPt, lastEnteredStateRecovering );
        }
        public boolean Abort( ContextImpl pContextImpl ){
            return MainStmHsm.Abort( pContextImpl );
        }
        public boolean IsFinished(){
            return MainStmHsm.nPseudostate == MainStmTop.MainStm;
        }

        public void Prepare( StateMachine pParent, String instanceName ){
            super.Prepare( pParent, "State_Machine_MainStm_MainStmTop", instanceName );
            MainStmHsm.pMain = this;
        }
} /* MainStmTop */
