/* File generated by Đức's ClasHStamP */
package design.model;

import java.io.*;
import java.util.*;
import design.model.*;
import design.base.*;
import design.abstracts.*;

public  class ContextImpl extends Context
{
    public  enum WeatherType {
        Sunny,                                                  
        Rainy,                                                  
        Cloudy,                                                 
        Snowy,                                                  
        Num
    };
    public static class onSpeedChangeParams extends EventParams{
        public Integer nKmPerHour;                              
        public WeatherType weatherType;                         
    };
    public enum EventId {
        E5,
        onAdasSwitch,
        Num
    };
    public boolean Start(){
        mainStm.Prepare( null, "mainStm" );
        boolean bResult = mainStm.Reset( this );
        bResult |= mainStm.StateDefaultTrans( this );
        return bResult;
    }
    public boolean EventProc( ContextImpl.EventId nEventId, EventParams pEventParams ){
        boolean bResult = mainStm.EventProc( this, nEventId, pEventParams );
        bResult |= mainStm.StateDefaultTrans( this );
        return bResult;
    }    protected void protectedMethod(
    ){
    } /* ContextImpl.protectedMethod */

    protected static void checkE1Params(
        EventParams e
    ){
    } /* ContextImpl.checkE1Params */
    public  ContextImpl(
        Integer _derivableAttribute,
        String _publicAttribute,
        Integer _privateAttribute,
        Integer _internalAttribute,
        Integer _readOnlyAttribute,
        ArrayList<Aggregration> _anAggregation,
        ArrayList<Composition> _aProtectedComposition
    ) {
        super( _derivableAttribute, _publicAttribute, _privateAttribute, _internalAttribute, _readOnlyAttribute, _anAggregation, _aProtectedComposition );
    mainStm = new MainStmTop();

    }                                                                                           
    MainStmTop mainStm;                                         
}
class _OnRgn1Hsm extends StateMachine {
        void OnRgn1_Entry( ContextImpl pContextImpl ){
            if( Enterable( MainStmTop.OnRgn1 ) ){
        if( !( ( MainStmTop )pMain ).lastEnteredStateRecovering && nTargetState == MainStmTop.OnRgn1 ){
            nPseudostate = MainStmTop.Initial4;
        }
        if ( ( ( MainStmTop )pMain ).lastEnteredStateRecovering ) {
            nPseudostate = lastEnteredState;
        }
            }
        }
        boolean OnRgn1_EventProc( ContextImpl pContextImpl, ContextImpl.EventId nEventId, EventParams pEventParams ){
            boolean bResult = false;
            if( !bHandled ){
                nSourceState = MainStmTop.OnRgn1;
            }
            bHandled |= bResult;
            wasHandled |= bResult;
            return bHandled;
        }
        void OnRgn1_Exit( ContextImpl pContextImpl ){
            if( Exitable( MainStmTop.OnRgn1 ) ){ 
            }
        }
        void State1_Entry( ContextImpl pContextImpl ){
            if( Enterable( MainStmTop.State1 ) ){
                OnRgn1_Entry( pContextImpl );
                DefaultEntryAction( pContextImpl, "MainStmTop	OnRgn1	397	340	161	61	30	30	1411	811	State1" );
            }
        }
        boolean State1_EventProc( ContextImpl pContextImpl, ContextImpl.EventId nEventId, EventParams pEventParams ){
            boolean bResult = false;
            if( !bHandled ){
                nSourceState = MainStmTop.State1;
                DefaultDoingAction( pContextImpl, "MainStmTop	OnRgn1	397	340	161	61	30	30	1411	811	State1" );
            }
            bHandled |= bResult;
            wasHandled |= bResult;
            return OnRgn1_EventProc( pContextImpl, nEventId, pEventParams );
        }
        void State1_Exit( ContextImpl pContextImpl ){
            if( Exitable( MainStmTop.State1 ) ){ 
                 DefaultExitAction( pContextImpl, "MainStmTop	OnRgn1	397	340	161	61	30	30	1411	811	State1" );
                OnRgn1_Exit( pContextImpl );
            }
        }
        void BgnTrans( ContextImpl pContextImpl, long targetState ){
            nTargetState = targetState;
            nPseudostate = targetState;
            if( nCurrentState == MainStmTop.OnRgn1 ) { OnRgn1_Exit( pContextImpl ); }
            else if( nCurrentState == MainStmTop.State1 ) { State1_Exit( pContextImpl ); }
            else {}
        }
        public boolean Reset(  ContextImpl pContextImpl ) {
            return Reset( pContextImpl, StateMachine.STATE_UNDEF, false );
        }
        public boolean Reset(  ContextImpl pContextImpl, boolean lastEnteredStateRecovering ) {
            return Reset( pContextImpl, StateMachine.STATE_UNDEF, lastEnteredStateRecovering );
        }
        public boolean Reset(  ContextImpl pContextImpl, long entryPt ) {
            return Reset( pContextImpl, entryPt, false );
        }
        public boolean Reset( ContextImpl pContextImpl, long entryPt, boolean lastEnteredStateRecovering ) {
            if( entryPt != StateMachine.STATE_UNDEF ){
                Req( entryPt );
                return false;
            }
            nPseudostate = MainStmTop.OnRgn1;
            bIsExternTrans = true;
            BgnTrans( pContextImpl, nPseudostate );
            EndTrans( pContextImpl );
            return true;
        }
        public boolean EventProc( ContextImpl pContextImpl, ContextImpl.EventId nEventId, EventParams pEventParams ){
            boolean bResult = false;
            nLCAState = StateMachine.STATE_UNDEF;
            bHandled = false;
            wasHandled = false;
            if( nCurrentState == MainStmTop.OnRgn1 ) { OnRgn1_EventProc( pContextImpl, nEventId, pEventParams ); }
            else if( nCurrentState == MainStmTop.State1 ) { State1_EventProc( pContextImpl, nEventId, pEventParams ); }
            else {}
            return bResult;
        }
        boolean Abort( ContextImpl pContextImpl ) {
            nSourceState = MainStmTop.OnRgn1;
            BgnTrans( pContextImpl, StateMachine.STATE_UNDEF );
            EndTrans( pContextImpl );
            return true;
        }
        void EndTrans( ContextImpl pContextImpl ){
            nCurrentState = nTargetState;
            bIsExternTrans = false;
            if( nCurrentState == MainStmTop.OnRgn1 ) { OnRgn1_Entry( pContextImpl ); }
            else if( nCurrentState == MainStmTop.State1 ) { State1_Entry( pContextImpl ); }
            else {}
        }
        boolean StateDefaultTrans( ContextImpl pContextImpl ){
            boolean bResult = false;
            nSourceState = nCurrentState;
            nLCAState = StateMachine.STATE_UNDEF;
        if ( nPseudostate == MainStmTop.Initial4  ) {
            BgnTrans( pContextImpl, MainStmTop.State1 );
                DefaultTransAction("436	295	480	340");
            EndTrans( pContextImpl );
            bResult |= true;
            }else if( nCurrentState != nPseudostate ){
                BgnTrans( pContextImpl, nPseudostate );
                EndTrans( pContextImpl );
                bResult = true;
            }else{
            }
            bHandled |= bResult;
            wasHandled |= bResult;
            ( ( MainStmTop )pMain ).lastEnteredStateRecovering = false;
            return bResult;
        }
}
class _MainStmTop extends StateMachine {
        void MainStm_Entry( ContextImpl pContextImpl ){
            if( Enterable( MainStmTop.MainStm ) ){
        if( !( ( MainStmTop )pMain ).lastEnteredStateRecovering && nTargetState == MainStmTop.MainStm ){
            nPseudostate = MainStmTop.MainStmInit;
        }
        if ( ( ( MainStmTop )pMain ).lastEnteredStateRecovering ) {
            nPseudostate = lastEnteredState;
        }
            }
        }
        boolean MainStm_EventProc( ContextImpl pContextImpl, ContextImpl.EventId nEventId, EventParams pEventParams ){
            boolean bResult = false;
            if( !bHandled ){
                nSourceState = MainStmTop.MainStm;
            }
            bHandled |= bResult;
            wasHandled |= bResult;
            return bHandled;
        }
        void MainStm_Exit( ContextImpl pContextImpl ){
            if( Exitable( MainStmTop.MainStm ) ){ 
            }
        }
        void Off_Entry( ContextImpl pContextImpl ){
            if( Enterable( MainStmTop.Off ) ){
                MainStm_Entry( pContextImpl );
                DefaultEntryAction( pContextImpl, "MainStmTop	MainStm	239	100	221	61	30	30	1411	811	Off" );
            }
        }
        boolean Off_EventProc( ContextImpl pContextImpl, ContextImpl.EventId nEventId, EventParams pEventParams ){
            boolean bResult = false;
            if( !bHandled ){
                nSourceState = MainStmTop.Off;
                DefaultDoingAction( pContextImpl, "MainStmTop	MainStm	239	100	221	61	30	30	1411	811	Off" );
                switch( nEventId ){
                case ContextImpl.EventId.onAdasSwitch:{
            BgnTrans( pContextImpl, MainStmTop.On );
                DefaultTransAction("280	161	280	240");
            EndTrans( pContextImpl );
            bResult |= true;
                } break;
                default: break;
                }
            }
            bHandled |= bResult;
            wasHandled |= bResult;
            return MainStm_EventProc( pContextImpl, nEventId, pEventParams );
        }
        void Off_Exit( ContextImpl pContextImpl ){
            if( Exitable( MainStmTop.Off ) ){ 
                 DefaultExitAction( pContextImpl, "MainStmTop	MainStm	239	100	221	61	30	30	1411	811	Off" );
                MainStm_Exit( pContextImpl );
            }
        }
        void On_Entry( ContextImpl pContextImpl ){
            if( Enterable( MainStmTop.On ) ){
                MainStm_Entry( pContextImpl );
                DefaultEntryAction( pContextImpl, "MainStmTop	MainStm	99	240	521	321	30	30	1411	811	On" );
        if( !( ( MainStmTop )pMain ).lastEnteredStateRecovering && nTargetState == MainStmTop.On ){
            nPseudostate = MainStmTop.OnInit;
        }
        ( ( MainStmTop )pMain ).OnRgn1Hsm.Reset( pContextImpl );
            }
        }
        boolean On_EventProc( ContextImpl pContextImpl, ContextImpl.EventId nEventId, EventParams pEventParams ){
            boolean bResult = false;
            bHandled |= ( ( MainStmTop )pMain ).OnRgn1Hsm.EventProc( pContextImpl, nEventId, pEventParams );
            if( !bHandled ){
                nSourceState = MainStmTop.On;
                DefaultDoingAction( pContextImpl, "MainStmTop	MainStm	99	240	521	321	30	30	1411	811	On" );
                switch( nEventId ){
                case ContextImpl.EventId.onAdasSwitch:{
            BgnTrans( pContextImpl, MainStmTop.Off );
                DefaultTransAction("420	240	420	161");
            EndTrans( pContextImpl );
            bResult |= true;
                } break;
                default: break;
                }
            }
            bHandled |= bResult;
            wasHandled |= bResult;
            return MainStm_EventProc( pContextImpl, nEventId, pEventParams );
        }
        void On_Exit( ContextImpl pContextImpl ){
            if( Exitable( MainStmTop.On ) ){ 
        ( ( MainStmTop )pMain ).OnRgn1Hsm.Abort( pContextImpl );
                 DefaultExitAction( pContextImpl, "MainStmTop	MainStm	99	240	521	321	30	30	1411	811	On" );
                MainStm_Exit( pContextImpl );
            }
        }
        void Deactive_Entry( ContextImpl pContextImpl ){
            if( Enterable( MainStmTop.Deactive ) ){
                On_Entry( pContextImpl );
                DefaultEntryAction( pContextImpl, "MainStmTop	MainStm	138	340	141	61	30	30	1411	811	Deactive" );
            }
        }
        boolean Deactive_EventProc( ContextImpl pContextImpl, ContextImpl.EventId nEventId, EventParams pEventParams ){
            boolean bResult = false;
            if( !bHandled ){
                nSourceState = MainStmTop.Deactive;
                DefaultDoingAction( pContextImpl, "MainStmTop	MainStm	138	340	141	61	30	30	1411	811	Deactive" );
                switch( nEventId ){
                case ContextImpl.EventId.E5:{
                DefaultTransAction("220	401	220	420	260	420	260	440");
                DefaultTransAction("220	401	220	420	260	420	260	440");
                DefaultTransAction("440	401	439	420	300	420	300	440");
            if (( ( MainStmTop )pMain ).OnRgn1Hsm.IsIn( MainStmTop.State1 )) {
                    DefaultTransAction("280	480	280	500");
                    DefaultTransAction("280	450	280	523	443	524");
                    DefaultTransAction("280	450	280	523	443	524");
                ( ( MainStmTop )pMain ).OnRgn1Hsm.Reset( pContextImpl, MainStmTop.OnRgn1 );
            }
                } break;
                default: break;
                }
            }
            bHandled |= bResult;
            wasHandled |= bResult;
            return On_EventProc( pContextImpl, nEventId, pEventParams );
        }
        void Deactive_Exit( ContextImpl pContextImpl ){
            if( Exitable( MainStmTop.Deactive ) ){ 
                 DefaultExitAction( pContextImpl, "MainStmTop	MainStm	138	340	141	61	30	30	1411	811	Deactive" );
                On_Exit( pContextImpl );
            }
        }
        void BgnTrans( ContextImpl pContextImpl, long targetState ){
            nTargetState = targetState;
            nPseudostate = targetState;
            if( nCurrentState == MainStmTop.MainStm ) { MainStm_Exit( pContextImpl ); }
            else if( nCurrentState == MainStmTop.Off ) { Off_Exit( pContextImpl ); }
            else if( nCurrentState == MainStmTop.Deactive ) { Deactive_Exit( pContextImpl ); }
            else if( nCurrentState == MainStmTop.On ) { On_Exit( pContextImpl ); }
            else {}
        }
        public boolean Reset(  ContextImpl pContextImpl ) {
            return Reset( pContextImpl, StateMachine.STATE_UNDEF, false );
        }
        public boolean Reset(  ContextImpl pContextImpl, boolean lastEnteredStateRecovering ) {
            return Reset( pContextImpl, StateMachine.STATE_UNDEF, lastEnteredStateRecovering );
        }
        public boolean Reset(  ContextImpl pContextImpl, long entryPt ) {
            return Reset( pContextImpl, entryPt, false );
        }
        public boolean Reset( ContextImpl pContextImpl, long entryPt, boolean lastEnteredStateRecovering ) {
            if( entryPt != StateMachine.STATE_UNDEF ){
                Req( entryPt );
                return false;
            }
            nPseudostate = MainStmTop.MainStm;
            bIsExternTrans = true;
            BgnTrans( pContextImpl, nPseudostate );
            EndTrans( pContextImpl );
            return true;
        }
        public boolean EventProc( ContextImpl pContextImpl, ContextImpl.EventId nEventId, EventParams pEventParams ){
            boolean bResult = false;
            nLCAState = StateMachine.STATE_UNDEF;
            bHandled = false;
            wasHandled = false;
            if( nCurrentState == MainStmTop.MainStm ) { MainStm_EventProc( pContextImpl, nEventId, pEventParams ); }
            else if( nCurrentState == MainStmTop.Off ) { Off_EventProc( pContextImpl, nEventId, pEventParams ); }
            else if( nCurrentState == MainStmTop.Deactive ) { Deactive_EventProc( pContextImpl, nEventId, pEventParams ); }
            else if( nCurrentState == MainStmTop.On ) { On_EventProc( pContextImpl, nEventId, pEventParams ); }
            else {}
            return bResult;
        }
        boolean Abort( ContextImpl pContextImpl ) {
            nSourceState = MainStmTop.MainStm;
            BgnTrans( pContextImpl, StateMachine.STATE_UNDEF );
            EndTrans( pContextImpl );
            return true;
        }
        void EndTrans( ContextImpl pContextImpl ){
            nCurrentState = nTargetState;
            bIsExternTrans = false;
            if( nCurrentState == MainStmTop.MainStm ) { MainStm_Entry( pContextImpl ); }
            else if( nCurrentState == MainStmTop.Off ) { Off_Entry( pContextImpl ); }
            else if( nCurrentState == MainStmTop.Deactive ) { Deactive_Entry( pContextImpl ); }
            else if( nCurrentState == MainStmTop.On ) { On_Entry( pContextImpl ); }
            else {}
        }
        boolean StateDefaultTrans( ContextImpl pContextImpl ){
            boolean bResult = false;
            nSourceState = nCurrentState;
            nLCAState = StateMachine.STATE_UNDEF;
        if ( nPseudostate == MainStmTop.MainStmInit  ) {
            BgnTrans( pContextImpl, MainStmTop.Off );
                DefaultTransAction("96	94	240	120");
            EndTrans( pContextImpl );
            bResult |= true;
        } else if ( nPseudostate == MainStmTop.OnInit  ) {
            BgnTrans( pContextImpl, MainStmTop.Deactive );
                DefaultTransAction("150	298	180	340");
            EndTrans( pContextImpl );
            bResult |= true;
            }else if( nCurrentState != nPseudostate ){
                BgnTrans( pContextImpl, nPseudostate );
                EndTrans( pContextImpl );
                bResult = true;
            }else{
            }
            bHandled |= bResult;
            wasHandled |= bResult;
            ( ( MainStmTop )pMain ).lastEnteredStateRecovering = false;
            return bResult;
        }
}
class MainStmTop extends BaseStmTop {
/* states' declaration */
        public static final long State1          = ( 1 <<  0 );
        public static final long Initial4        = ( 1 <<  1 );
        public static final long OnRgn1          = ( State1 | Initial4 );
/* states' declaration */
        public static final long Off             = ( 1 <<  0 );
        public static final long MainStmInit     = ( 1 <<  1 );
        public static final long Deactive        = ( 1 <<  2 );
        public static final long OnInit          = ( 1 <<  3 );
        public static final long On              = ( Deactive | OnInit );
        public static final long MainStm         = ( Off | MainStmInit | On );
        _MainStmTop MainStmHsm = new _MainStmTop();             
        _OnRgn1Hsm OnRgn1Hsm = new _OnRgn1Hsm();                

        public boolean EventProc( ContextImpl pContextImpl, ContextImpl.EventId nEventId, EventParams pEventParams ){
            return MainStmHsm.EventProc( pContextImpl, nEventId, pEventParams );
        }
        public boolean StateDefaultTrans( ContextImpl pContextImpl ){
            boolean bResult;
            while( true ){
                bResult = false;
                bResult |= OnRgn1Hsm.StateDefaultTrans( pContextImpl );
                bResult |= MainStmHsm.StateDefaultTrans( pContextImpl );
                if( bResult == false ){
                    break;
                }
            }
            return bResult;
        }
        public boolean Reset( ContextImpl pContextImpl ){
            return MainStmHsm.Reset( pContextImpl, StateMachine.STATE_UNDEF, false );
        }
        public boolean Reset( ContextImpl pContextImpl, long entryPt, boolean lastEnteredStateRecovering ){
            MainStmHsm.Abort( pContextImpl );
            return MainStmHsm.Reset( pContextImpl, entryPt, lastEnteredStateRecovering );
        }
        public boolean Abort( ContextImpl pContextImpl ){
            return MainStmHsm.Abort( pContextImpl );
        }
        public boolean IsFinished(){
            return MainStmHsm.nPseudostate == MainStmTop.MainStm;
        }

        public void Prepare( StateMachine pParent, String instanceName ){
            super.Prepare( pParent, "State_Machine_MainStm_MainStmTop", instanceName );
            MainStmHsm.pMain = this;
            OnRgn1Hsm.pMain = this;
        }
} /* MainStmTop */
