/* File generated by Đức's ClasHStamP */
package design.model;

import java.io.*;
import java.util.*;
import design.abstracts.*;
import design.interfaces.*;
import design.model.*;

public  class Context extends BaseClass implements Interface2, Interface1
{
    private static Integer classOrStaticAttribute;              
    private static Integer[] initializedStaticArray = { 1, 2, 3 };
    private static Integer finalConstantAttribute = 5;          
    public static void classOrStaticMethod(
    ){
    } /* Context.classOrStaticMethod */
    public void publicMethod(
    ){
    } /* Context.publicMethod */

    private void privateLeafMethod(
    ){
    } /* Context.privateLeafMethod */
    public void methodWithParams(
        String parm1,
        Integer parm2
    ){
    	if (parm1.equals("internalAttribute")) {
			internalAttribute = parm2;
		}
    } /* Context.methodWithParams */
    public UsedDependency methodReturnsSomething(
    ){
    	return null;
    } /* Context.methodReturnsSomething */
    public void methodThrowsException(
    ){
    } /* Context.methodThrowsException */
    public void finalMethod(
    ){
    } /* Context.finalMethod */
    protected void protectedMethod(
    ){
    } /* Context.protectedMethod */

    protected void packageVisibleMethod(
    ){
    } /* Context.packageVisibleMethod */

    public  Context(
        Integer _derivableAttribute,
        String _publicAttribute,
        Integer _privateAttribute,
        Integer _internalAttribute,
        Integer _readOnlyAttribute,
        ArrayList<Aggregration> _anAggregation,
        ArrayList<Composition> _aProtectedComposition
    ) {
        super( _derivableAttribute );

        publicAttribute = _publicAttribute;
        privateAttribute = _privateAttribute;
        internalAttribute = _internalAttribute;
        isInitializedAttribute = true;
        readOnlyAttribute = _readOnlyAttribute;
        anAggregation = _anAggregation;
        aProtectedComposition = _aProtectedComposition;
    }                                                                                           
    public String publicAttribute;                              
    private Integer privateAttribute;                           
    Integer internalAttribute;                                  
    private Boolean isInitializedAttribute;                     
    private Integer readOnlyAttribute;                          
    private ArrayList<Aggregration> anAggregation;                 
    protected ArrayList<Composition> aProtectedComposition;        
}
