/* File generated by Đức's ClasHStamP */
package design.model;

import java.io.*;
import java.util.*;

public  class UsedDependency
{
    public  UsedDependency(
        Integer _attribute6
    ){
        attribute6 = _attribute6;
    }                                                                                           
    private Integer attribute6;                                 
}
