/* File generated by Đức's ClasHStamP */
import type { Integer, long, Boolean, String, ResetArgs } from "#all_notations/java_sample00/stdtype/stdtype";
 /* class.name */
        export class AFriend
        { /* class.begin */
 /* friend.ext1st */ /* friend.end */            constructor( /* constructor.name */ /* __s_attr.ext1st */
                _attribute3: Integer /* constructor.begin */
            ){ /* __s_attr.begin */
                this.attribute3 = _attribute3; /* constructor.end */
            }                                                                                   
 /* attr_group.name */ /* attr_group.begin */            attribute3: Integer;                                 /* __s_attr.name */
 /* attr_group.end */        } /* class.end */
