/* File generated by Đức's ClasHStamP */
import type { Integer, long, Boolean, String, ResetArgs } from "#all_notations/java_sample00/stdtype/stdtype";
 /* class.name */
        export class CalledDependency
        { /* class.begin */
 /* friend.ext1st */ /* friend.end */            constructor( /* constructor.name */ /* __s_attr.ext1st */
                _attribute0: Integer /* constructor.begin */
            ){ /* __s_attr.begin */
                this.attribute0 = _attribute0; /* constructor.end */
            }                                                                                   
 /* attr_group.name */ /* attr_group.begin */            private attribute0: Integer;                         /* __s_attr.name */
 /* attr_group.end */        } /* class.end */
