/* File generated by Đức's ClasHStamP */
import type { Integer, long, Boolean, String, ResetArgs } from "#all_notations/java_sample00/stdtype/stdtype";
import { BaseClass } from "#all_notations/java_sample00/abstracts/BaseClass";
import { Interface2 } from "#all_notations/java_sample00/interfaces/Interface2";
import { Interface1 } from "#all_notations/java_sample00/interfaces/Interface1";
import { Aggregration } from "#all_notations/java_sample00/model/Aggregration";
import { Composition } from "#all_notations/java_sample00/model/Composition";
import { UsedDependency } from "#all_notations/java_sample00/model/UsedDependency";
 /* class.name */
export class Context /* inheritance.begin */ extends BaseClass /* inheritance.name */ /* inheritance.end */ implements Interface2 /* inheritance.ext1st */, Interface1 /* inheritance.extnxt */
{ /* class.begin */
    private static classOrStaticAttribute: Integer;              /* s_s_attr.end */
    private static initializedStaticArray: Integer[] = [1, 2, 3]; /* sms_attr.name */
    private static finalConstantAttribute: Integer = 5;          /* s_s_attr.name */
    public staticclassOrStaticMethod( /* s_b_oper.name */ /* s_b_oper.begin */
    ): void {
    } /* Context.classOrStaticMethod */ /* s_b_oper.end */
    public publicMethod( /* __b_oper.name */ /* __b_oper.begin */
    ): void {
    } /* Context.publicMethod */ /* __b_oper.end */

    private privateLeafMethod( /* l_i_oper.name */ /* l_i_oper.begin */
    ): void {
    } /* Context.privateLeafMethod */ /* l_i_oper.end */
    public methodWithParams( /* l_b_oper.name */ /* l_b_oper.ext1st */
        parm1: String, /* l_b_oper.extnxt */
        parm2: Integer /* l_b_oper.begin */
    ): void {
    } /* Context.methodWithParams */ /* l_b_oper.end */
    public methodReturnsSomething( /* l_b_oper.name */ /* l_b_oper.begin */
    ): UsedDependency {
		return new UsedDependency(0);
    } /* Context.methodReturnsSomething */ /* l_b_oper.end */
    public methodThrowsException( /* l_b_oper.name */ /* l_b_oper.begin */
    ): void {
    } /* Context.methodThrowsException */ /* l_b_oper.end */
    public finalMethod( /* l_b_oper.name */ /* l_b_oper.begin */
    ): void {
    } /* Context.finalMethod */ /* l_b_oper.end */
 /* friend.ext1st */ /* friend.extnxt */ /* friend.end */    protected protectedMethod( /* __c_oper.name */ /* __c_oper.begin */
    ): void {
    } /* Context.protectedMethod */ /* __c_oper.end */

    protected packageVisibleMethod( /* __c_oper.name */ /* __c_oper.begin */
    ): void {
    } /* Context.packageVisibleMethod */ /* __c_oper.end */

    constructor( /* constructor.name */ /* __s_attr.ext1st */
        _derivableAttribute: Integer, /* __s_attr.extnxt */
        _publicAttribute: String, /* __s_attr.extnxt */
        _privateAttribute: Integer, /* __s_attr.extnxt */
        _internalAttribute: Integer, /* __s_attr.extnxt */
        _readOnlyAttribute: Integer, /* _mr_attr.extnxt */
        _anAggregation: Aggregration[] | undefined, /* _mr_attr.extnxt */
        _aProtectedComposition: Composition[] | undefined /* ctor_call.name */
    ) {
        super( _derivableAttribute /* ctor_call.ext1st */ );
 /* constructor.extnxt */ /* __s_attr.end */
        this.publicAttribute = _publicAttribute; /* __s_attr.end */
        this.privateAttribute = _privateAttribute; /* __s_attr.end */
        this.internalAttribute = _internalAttribute; /* __s_attr.end */
        this.isInitializedAttribute = true; /* __s_attr.end */
        this.readOnlyAttribute = _readOnlyAttribute; /* _mr_attr.end */
        this.anAggregation = _anAggregation; /* _mr_attr.end */
        this.aProtectedComposition = _aProtectedComposition; /* constructor.end */
    }                                                                                           
 /* vptr_impl.name */ /* attr_group.name */ /* attr_group.extnxt */    public publicAttribute: String;                              /* __s_attr.name */
    private privateAttribute: Integer;                           /* __s_attr.name */
    internalAttribute: Integer;                                  /* __s_attr.name */
    private isInitializedAttribute: Boolean;                     /* __s_attr.name */
    private readOnlyAttribute: Integer;                          /* __s_attr.name */
    private anAggregation: Aggregration[] | undefined;              /* _mr_attr.name */
    protected aProtectedComposition: Composition[] | undefined;     /* _mr_attr.name */
 /* attr_group.end */} /* class.end */
