/* File generated by Đức's ClasHStamP */
import type { Integer, long, Boolean, String, ResetArgs } from "#all_notations/java_sample00/stdtype/stdtype";
import { Context } from "#all_notations/java_sample00/model/Context";
import { EventParams } from "#all_notations/java_sample00/base/EventParams";
import { BaseClass } from "#all_notations/java_sample00/abstracts/BaseClass";
import { Aggregration } from "#all_notations/java_sample00/model/Aggregration";
import { Composition } from "#all_notations/java_sample00/model/Composition";
import { BaseStmTop } from "#all_notations/java_sample00/stdtype/stdtype"; /* statemachine.name */
import { StateMachine } from "#all_notations/java_sample00/base/StateMachine";
 /* class.name */
export class ContextImpl /* inheritance.begin */ extends Context /* inheritance.name */
{ /* class.begin */
 /* event_decl.name */        public static readonly E0 = 0; /* event_decl.ext1st */
        public static readonly E1 = 1; /* event_decl.extnxt */
        public static readonly E2 = 2; /* event_decl.extnxt */
        public static readonly E3 = 3; /* event_decl.extnxt */
        public static readonly E4 = 4; /* event_decl.extnxt */
        public static readonly E5 = 5; /* event_decl.extnxt */
    public Start(): boolean{ /* event_decl.end */
        this.mainStm.Prepare( undefined );
        let bResult: boolean = this.mainStm.Reset( this );
        bResult ||= this.mainStm.StateDefaultTrans( this );
        return bResult;
    }
    public EventProc( nEventId: number, pEventParams: EventParams ): boolean{
        let bResult: boolean = this.mainStm.EventProc( this, nEventId, pEventParams );
        bResult ||= this.mainStm.StateDefaultTrans( this );
        return bResult;
    } /* friend.ext1st */ /* friend.extnxt */ /* friend.end */    protected protectedMethod( /* __c_oper.name */ /* __c_oper.begin */
    ): void {
    } /* ContextImpl.protectedMethod */ /* __c_oper.end */

    protected staticcheckE1Params( /* s_c_oper.name */ /* s_c_oper.ext1st */
        e: EventParams /* s_c_oper.begin */
    ): void {
    } /* ContextImpl.checkE1Params */ /* s_c_oper.end */
    constructor( /* constructor.name */ /* __s_attr.ext1st */
        _derivableAttribute: Integer, /* __s_attr.extnxt */
        _publicAttribute: String, /* __s_attr.extnxt */
        _privateAttribute: Integer, /* __s_attr.extnxt */
        _internalAttribute: Integer, /* __s_attr.extnxt */
        _readOnlyAttribute: Integer, /* _mr_attr.extnxt */
        _anAggregation: Aggregration[] | undefined, /* _mr_attr.extnxt */
        _aProtectedComposition: Composition[] | undefined /* ctor_call.name */
    ) {
        super( _derivableAttribute /* ctor_call.ext1st */, _publicAttribute /* ctor_call.extnxt */, _privateAttribute /* ctor_call.extnxt */, _internalAttribute /* ctor_call.extnxt */, _readOnlyAttribute /* ctor_call.extnxt */, _anAggregation /* ctor_call.extnxt */, _aProtectedComposition /* ctor_call.extnxt */ );
 /* constructor.extnxt */    this.mainStm = new MainStmTop(); /* statemachine.extnxt */
 /* constructor.end */
    }                                                                                           
 /* vptr_impl.name */ /* attr_group.name */ /* attr_group.extnxt */    mainStm: MainStmTop;                                         /* statemachine.ext1st */
 /* attr_group.end */} /* class.end */
class _SubStmTop extends StateMachine { /* region.end */
        SubStm_Entry( pContextImpl: ContextImpl ): void{ /* trans_top.name */
            if( this.Enterable( SubStmTop.SubStm ) ){
        if( !( this.pMain as SubStmTop ).lastEnteredStateRecovering && this.nTargetState == SubStmTop.SubStm ){ /* state_action.name */
            this.nPseudostate = SubStmTop.SubStmInit;
        }
        if ( ( this.pMain as SubStmTop ).lastEnteredStateRecovering ) { /* deep_hist.end */
            this.nPseudostate = this.lastEnteredState;
        }
            }
        }
        SubStm_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            if( !this.bHandled ){
                this.nSourceState = SubStmTop.SubStm;
            } /* trans_top.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.bHandled;
        }
        SubStm_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( SubStmTop.SubStm ) ){ 
            }
        }
        S101_Entry( pContextImpl: ContextImpl ): void{ /* transition.name */
            if( this.Enterable( SubStmTop.S101 ) ){
                this.SubStm_Entry( pContextImpl );
                this.DefaultEntryAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/SubStm/	209	30	121	81	30	30	700	300	S101" );
            }
        }
        S101_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            if( !this.bHandled ){
                this.nSourceState = SubStmTop.S101;
                this.DefaultDoingAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/SubStm/	209	30	121	81	30	30	700	300	S101" );
                switch( nEventId ){ /* transition.ext1st */
                case ContextImpl.E5:{
            this.BgnTrans( pContextImpl, SubStmTop.S102 ); /* trans_action.begin */
            this.EndTrans( pContextImpl );
            bResult ||= true;
                } break; /* transition.begin */
                default: break;
                }
            } /* transition.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.SubStm_EventProc( pContextImpl, nEventId, pEventParams );
        }
        S101_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( SubStmTop.S101 ) ){ 
                 this.DefaultExitAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/SubStm/	209	30	121	81	30	30	700	300	S101" );
                this.SubStm_Exit( pContextImpl );
            }
        }
        S102_Entry( pContextImpl: ContextImpl ): void{ /* transition.name */
            if( this.Enterable( SubStmTop.S102 ) ){
                this.SubStm_Entry( pContextImpl );
                this.DefaultEntryAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/SubStm/	449	90	121	81	30	30	700	300	S102" );
            }
        }
        S102_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            if( !this.bHandled ){
                this.nSourceState = SubStmTop.S102;
                this.DefaultDoingAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/SubStm/	449	90	121	81	30	30	700	300	S102" );
            } /* transition.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.SubStm_EventProc( pContextImpl, nEventId, pEventParams );
        }
        S102_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( SubStmTop.S102 ) ){ 
                 this.DefaultExitAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/SubStm/	449	90	121	81	30	30	700	300	S102" );
                this.SubStm_Exit( pContextImpl );
            }
        }
        BgnTrans( pContextImpl: ContextImpl, targetState: long ): void{ /* state_exit.name */
            this.nTargetState = targetState;
            this.nPseudostate = targetState;
            if( this.nCurrentState == SubStmTop.SubStm ) { this.SubStm_Exit( pContextImpl ); } /* state_exit.ext1st */
            else if( this.nCurrentState == SubStmTop.S101 ) { this.S101_Exit( pContextImpl ); } /* state_exit.extnxt */
            else if( this.nCurrentState == SubStmTop.S102 ) { this.S102_Exit( pContextImpl ); } /* state_exit.extnxt */
            else {} /* state_exit.begin */
        } /* state_exit.end */
        public Reset( pContextImpl: ContextImpl, args: ResetArgs = {} ): boolean { /* state_impl.name */
            const entryPt = args.entryPt ?? StateMachine.STATE_UNDEF;
            const lastEnteredStateRecovering = args.lastEnteredStateRecovering ?? false;
            if( entryPt != StateMachine.STATE_UNDEF ){
                this.Req( entryPt );
                return false;
            }
            this.nPseudostate = SubStmTop.SubStm;
            this.bIsExternTrans = true;
            this.BgnTrans( pContextImpl, this.nPseudostate );
            this.EndTrans( pContextImpl );
            return true;
        }
        public EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            this.nLCAState = StateMachine.STATE_UNDEF;
            this.bHandled = false;
            this.wasHandled = false;
            if( this.nCurrentState == SubStmTop.SubStm ) { this.SubStm_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.ext1st */
            else if( this.nCurrentState == SubStmTop.S101 ) { this.S101_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.extnxt */
            else if( this.nCurrentState == SubStmTop.S102 ) { this.S102_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.extnxt */
            else {} /* state_impl.begin */
            return bResult; /* state_impl.end */
        }
        Abort( pContextImpl: ContextImpl ): boolean {
            this.nSourceState = SubStmTop.SubStm;
            this.BgnTrans( pContextImpl, StateMachine.STATE_UNDEF );
            this.EndTrans( pContextImpl );
            return true;
        }
        EndTrans( pContextImpl: ContextImpl ): void{ /* state_entry.name */
            this.nCurrentState = this.nTargetState;
            this.bIsExternTrans = false;
            if( this.nCurrentState == SubStmTop.SubStm ) { this.SubStm_Entry( pContextImpl ); } /* state_entry.ext1st */
            else if( this.nCurrentState == SubStmTop.S101 ) { this.S101_Entry( pContextImpl ); } /* state_entry.extnxt */
            else if( this.nCurrentState == SubStmTop.S102 ) { this.S102_Entry( pContextImpl ); } /* state_entry.extnxt */
            else {} /* state_entry.begin */
        } /* state_entry.end */
        StateDefaultTrans( pContextImpl: ContextImpl ): boolean{ /* default_trans.name */
            let bResult: boolean = false;
            this.nSourceState = this.nCurrentState;
            this.nLCAState = StateMachine.STATE_UNDEF;
        if ( this.nPseudostate == SubStmTop.SubStmInit  ) { /* branch.ext1st */
            this.BgnTrans( pContextImpl, SubStmTop.S101 ); /* trans_action.begin */
            this.EndTrans( pContextImpl );
            bResult ||= true;
        } else if ( this.nCurrentState == SubStmTop.S102 && this.nPseudostate == SubStmTop.S102   /* default_trans.extnxt */) { /* branch.extnxt */
            this.BgnTrans( pContextImpl, SubStmTop.SubStm ); /* trans_action.begin */
            ( this.pMain as SubStmTop ).pParentStm?.Req( SubStmTop.Exit1 ); /* substm.end */
            this.EndTrans( pContextImpl );
            bResult ||= true;
            }else if( this.nCurrentState != this.nPseudostate ){ /* default_trans.begin */
                this.BgnTrans( pContextImpl, this.nPseudostate );
                this.EndTrans( pContextImpl );
                bResult = true;
            }else{
            }
            this.bHandled ||= bResult; /* default_trans.end */
            this.wasHandled ||= bResult;
            ( this.pMain as SubStmTop ).lastEnteredStateRecovering = false;
            return bResult;
        }
}
class _S8Rgn1Hsm extends StateMachine { /* region.end */
        S8Rgn1_Entry( pContextImpl: ContextImpl ): void{ /* trans_top.name */
            if( this.Enterable( MainStmTop.S8Rgn1 ) ){
        if( !( this.pMain as MainStmTop ).lastEnteredStateRecovering && this.nTargetState == MainStmTop.S8Rgn1 ){ /* state_action.name */
            this.nPseudostate = MainStmTop.S82Init;
        }
        if ( ( this.pMain as MainStmTop ).lastEnteredStateRecovering ) { /* deep_hist.end */
            this.nPseudostate = this.lastEnteredState;
        }
            }
        }
        S8Rgn1_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            if( !this.bHandled ){
                this.nSourceState = MainStmTop.S8Rgn1;
            } /* trans_top.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.bHandled;
        }
        S8Rgn1_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( MainStmTop.S8Rgn1 ) ){ 
            }
        }
        S821_Entry( pContextImpl: ContextImpl ): void{ /* transition.name */
            if( this.Enterable( MainStmTop.S821 ) ){
                this.S8Rgn1_Entry( pContextImpl );
                this.DefaultEntryAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	479	16	121	81	30	30	1461	931	S821" );
            }
        }
        S821_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            if( !this.bHandled ){
                this.nSourceState = MainStmTop.S821;
                this.DefaultDoingAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	479	16	121	81	30	30	1461	931	S821" );
                switch( nEventId ){ /* transition.ext1st */
                case ContextImpl.E2:{
            if (( this.pMain as MainStmTop ).MainStmHsm.IsIn( MainStmTop.S812 ) /* trans_action.ext1st */) { /* branch.ext1st */
                ( this.pMain as MainStmTop ).MainStmHsm.Reset( pContextImpl, { entryPt: MainStmTop.S811 } ); /* region.begin */
            } /* branch.end */
                } break; /* transition.begin */
                default: break;
                }
            } /* transition.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.S8Rgn1_EventProc( pContextImpl, nEventId, pEventParams );
        }
        S821_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( MainStmTop.S821 ) ){ 
                 this.DefaultExitAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	479	16	121	81	30	30	1461	931	S821" );
                this.S8Rgn1_Exit( pContextImpl );
            }
        }
        S822_Entry( pContextImpl: ContextImpl ): void{ /* transition.name */
            if( this.Enterable( MainStmTop.S822 ) ){
                this.S8Rgn1_Entry( pContextImpl );
                this.DefaultEntryAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	119	16	121	81	30	30	1461	931	S822" );
            }
        }
        S822_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            if( !this.bHandled ){
                this.nSourceState = MainStmTop.S822;
                this.DefaultDoingAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	119	16	121	81	30	30	1461	931	S822" );
            } /* transition.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.S8Rgn1_EventProc( pContextImpl, nEventId, pEventParams );
        }
        S822_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( MainStmTop.S822 ) ){ 
                 this.DefaultExitAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	119	16	121	81	30	30	1461	931	S822" );
                this.S8Rgn1_Exit( pContextImpl );
            }
        }
        BgnTrans( pContextImpl: ContextImpl, targetState: long ): void{ /* state_exit.name */
            this.nTargetState = targetState;
            this.nPseudostate = targetState;
            if( this.nCurrentState == MainStmTop.S8Rgn1 ) { this.S8Rgn1_Exit( pContextImpl ); } /* state_exit.ext1st */
            else if( this.nCurrentState == MainStmTop.S821 ) { this.S821_Exit( pContextImpl ); } /* state_exit.extnxt */
            else if( this.nCurrentState == MainStmTop.S822 ) { this.S822_Exit( pContextImpl ); } /* state_exit.extnxt */
            else {} /* state_exit.begin */
        } /* state_exit.end */
        public Reset( pContextImpl: ContextImpl, args: ResetArgs = {} ): boolean { /* state_impl.name */
            const entryPt = args.entryPt ?? StateMachine.STATE_UNDEF;
            const lastEnteredStateRecovering = args.lastEnteredStateRecovering ?? false;
            if( entryPt != StateMachine.STATE_UNDEF ){
                this.Req( entryPt );
                return false;
            }
            this.nPseudostate = MainStmTop.S8Rgn1;
            this.bIsExternTrans = true;
            this.BgnTrans( pContextImpl, this.nPseudostate );
            this.EndTrans( pContextImpl );
            return true;
        }
        public EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            this.nLCAState = StateMachine.STATE_UNDEF;
            this.bHandled = false;
            this.wasHandled = false;
            if( this.nCurrentState == MainStmTop.S8Rgn1 ) { this.S8Rgn1_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.ext1st */
            else if( this.nCurrentState == MainStmTop.S821 ) { this.S821_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.extnxt */
            else if( this.nCurrentState == MainStmTop.S822 ) { this.S822_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.extnxt */
            else {} /* state_impl.begin */
            return bResult; /* state_impl.end */
        }
        Abort( pContextImpl: ContextImpl ): boolean {
            this.nSourceState = MainStmTop.S8Rgn1;
            this.BgnTrans( pContextImpl, StateMachine.STATE_UNDEF );
            this.EndTrans( pContextImpl );
            return true;
        }
        EndTrans( pContextImpl: ContextImpl ): void{ /* state_entry.name */
            this.nCurrentState = this.nTargetState;
            this.bIsExternTrans = false;
            if( this.nCurrentState == MainStmTop.S8Rgn1 ) { this.S8Rgn1_Entry( pContextImpl ); } /* state_entry.ext1st */
            else if( this.nCurrentState == MainStmTop.S821 ) { this.S821_Entry( pContextImpl ); } /* state_entry.extnxt */
            else if( this.nCurrentState == MainStmTop.S822 ) { this.S822_Entry( pContextImpl ); } /* state_entry.extnxt */
            else {} /* state_entry.begin */
        } /* state_entry.end */
        StateDefaultTrans( pContextImpl: ContextImpl ): boolean{ /* default_trans.name */
            let bResult: boolean = false;
            this.nSourceState = this.nCurrentState;
            this.nLCAState = StateMachine.STATE_UNDEF;
        if ( this.nPseudostate == MainStmTop.S82Init  ) { /* branch.ext1st */
            this.BgnTrans( pContextImpl, MainStmTop.S821 ); /* trans_action.begin */
            this.EndTrans( pContextImpl );
            bResult ||= true;
            }else if( this.nCurrentState != this.nPseudostate ){ /* default_trans.begin */
                this.BgnTrans( pContextImpl, this.nPseudostate );
                this.EndTrans( pContextImpl );
                bResult = true;
            }else{
            }
            this.bHandled ||= bResult; /* default_trans.end */
            this.wasHandled ||= bResult;
            ( this.pMain as MainStmTop ).lastEnteredStateRecovering = false;
            return bResult;
        }
}
class _S71Rgn1Hsm extends StateMachine { /* region.end */
        S71Rgn1_Entry( pContextImpl: ContextImpl ): void{ /* trans_top.name */
            if( this.Enterable( MainStmTop.S71Rgn1 ) ){
        if( !( this.pMain as MainStmTop ).lastEnteredStateRecovering && this.nTargetState == MainStmTop.S71Rgn1 ){ /* state_action.name */
            this.nPseudostate = MainStmTop.S712Init;
        }
        if ( ( this.pMain as MainStmTop ).lastEnteredStateRecovering ) { /* deep_hist.end */
            this.nPseudostate = this.lastEnteredState;
        }
            }
        }
        S71Rgn1_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            if( !this.bHandled ){
                this.nSourceState = MainStmTop.S71Rgn1;
            } /* trans_top.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.bHandled;
        }
        S71Rgn1_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( MainStmTop.S71Rgn1 ) ){ 
            }
        }
        S7121_Entry( pContextImpl: ContextImpl ): void{ /* transition.name */
            if( this.Enterable( MainStmTop.S7121 ) ){
                this.S71Rgn1_Entry( pContextImpl );
                this.DefaultEntryAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	19	40	81	61	30	30	1461	931	S7121" );
            }
        }
        S7121_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            if( !this.bHandled ){
                this.nSourceState = MainStmTop.S7121;
                this.DefaultDoingAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	19	40	81	61	30	30	1461	931	S7121" );
                switch( nEventId ){ /* transition.ext1st */
                case ContextImpl.E5:{
            this.BgnTrans( pContextImpl, MainStmTop.S7122 ); /* trans_action.begin */
            this.EndTrans( pContextImpl );
            bResult ||= true;
                } break; /* transition.begin */
                default: break;
                }
            } /* transition.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.S71Rgn1_EventProc( pContextImpl, nEventId, pEventParams );
        }
        S7121_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( MainStmTop.S7121 ) ){ 
                 this.DefaultExitAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	19	40	81	61	30	30	1461	931	S7121" );
                this.S71Rgn1_Exit( pContextImpl );
            }
        }
        S7122_Entry( pContextImpl: ContextImpl ): void{ /* transition.name */
            if( this.Enterable( MainStmTop.S7122 ) ){
                this.S71Rgn1_Entry( pContextImpl );
                this.DefaultEntryAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	19	140	81	61	30	30	1461	931	S7122" );
            }
        }
        S7122_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            if( !this.bHandled ){
                this.nSourceState = MainStmTop.S7122;
                this.DefaultDoingAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	19	140	81	61	30	30	1461	931	S7122" );
            } /* transition.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.S71Rgn1_EventProc( pContextImpl, nEventId, pEventParams );
        }
        S7122_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( MainStmTop.S7122 ) ){ 
                 this.DefaultExitAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	19	140	81	61	30	30	1461	931	S7122" );
                this.S71Rgn1_Exit( pContextImpl );
            }
        }
        BgnTrans( pContextImpl: ContextImpl, targetState: long ): void{ /* state_exit.name */
            this.nTargetState = targetState;
            this.nPseudostate = targetState;
            if( this.nCurrentState == MainStmTop.S71Rgn1 ) { this.S71Rgn1_Exit( pContextImpl ); } /* state_exit.ext1st */
            else if( this.nCurrentState == MainStmTop.S7121 ) { this.S7121_Exit( pContextImpl ); } /* state_exit.extnxt */
            else if( this.nCurrentState == MainStmTop.S7122 ) { this.S7122_Exit( pContextImpl ); } /* state_exit.extnxt */
            else {} /* state_exit.begin */
        } /* state_exit.end */
        public Reset( pContextImpl: ContextImpl, args: ResetArgs = {} ): boolean { /* state_impl.name */
            const entryPt = args.entryPt ?? StateMachine.STATE_UNDEF;
            const lastEnteredStateRecovering = args.lastEnteredStateRecovering ?? false;
            if( entryPt != StateMachine.STATE_UNDEF ){
                this.Req( entryPt );
                return false;
            }
            this.nPseudostate = MainStmTop.S71Rgn1;
            this.bIsExternTrans = true;
            this.BgnTrans( pContextImpl, this.nPseudostate );
            this.EndTrans( pContextImpl );
            return true;
        }
        public EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            this.nLCAState = StateMachine.STATE_UNDEF;
            this.bHandled = false;
            this.wasHandled = false;
            if( this.nCurrentState == MainStmTop.S71Rgn1 ) { this.S71Rgn1_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.ext1st */
            else if( this.nCurrentState == MainStmTop.S7121 ) { this.S7121_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.extnxt */
            else if( this.nCurrentState == MainStmTop.S7122 ) { this.S7122_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.extnxt */
            else {} /* state_impl.begin */
            return bResult; /* state_impl.end */
        }
        Abort( pContextImpl: ContextImpl ): boolean {
            this.nSourceState = MainStmTop.S71Rgn1;
            this.BgnTrans( pContextImpl, StateMachine.STATE_UNDEF );
            this.EndTrans( pContextImpl );
            return true;
        }
        EndTrans( pContextImpl: ContextImpl ): void{ /* state_entry.name */
            this.nCurrentState = this.nTargetState;
            this.bIsExternTrans = false;
            if( this.nCurrentState == MainStmTop.S71Rgn1 ) { this.S71Rgn1_Entry( pContextImpl ); } /* state_entry.ext1st */
            else if( this.nCurrentState == MainStmTop.S7121 ) { this.S7121_Entry( pContextImpl ); } /* state_entry.extnxt */
            else if( this.nCurrentState == MainStmTop.S7122 ) { this.S7122_Entry( pContextImpl ); } /* state_entry.extnxt */
            else {} /* state_entry.begin */
        } /* state_entry.end */
        StateDefaultTrans( pContextImpl: ContextImpl ): boolean{ /* default_trans.name */
            let bResult: boolean = false;
            this.nSourceState = this.nCurrentState;
            this.nLCAState = StateMachine.STATE_UNDEF;
        if ( this.nPseudostate == MainStmTop.S712Init  ) { /* branch.ext1st */
            this.BgnTrans( pContextImpl, MainStmTop.S7121 ); /* trans_action.begin */
            this.EndTrans( pContextImpl );
            bResult ||= true;
            }else if( this.nCurrentState != this.nPseudostate ){ /* default_trans.begin */
                this.BgnTrans( pContextImpl, this.nPseudostate );
                this.EndTrans( pContextImpl );
                bResult = true;
            }else{
            }
            this.bHandled ||= bResult; /* default_trans.end */
            this.wasHandled ||= bResult;
            ( this.pMain as MainStmTop ).lastEnteredStateRecovering = false;
            return bResult;
        }
}
class _MainStmTop extends StateMachine { /* region.end */
        MainStm_Entry( pContextImpl: ContextImpl ): void{ /* trans_top.name */
            if( this.Enterable( MainStmTop.MainStm ) ){
        if( !( this.pMain as MainStmTop ).lastEnteredStateRecovering && this.nTargetState == MainStmTop.MainStm ){ /* state_action.name */
            this.nPseudostate = MainStmTop.MainStmInit;
        }
        if ( ( this.pMain as MainStmTop ).lastEnteredStateRecovering ) { /* deep_hist.end */
            this.nPseudostate = this.lastEnteredState;
        }
            }
        }
        MainStm_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            if( !this.bHandled ){
                this.nSourceState = MainStmTop.MainStm;
            } /* trans_top.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.bHandled;
        }
        MainStm_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( MainStmTop.MainStm ) ){ 
            }
        }
        S1_Entry( pContextImpl: ContextImpl ): void{ /* transition.name */
            if( this.Enterable( MainStmTop.S1 ) ){
                this.MainStm_Entry( pContextImpl );
                this.DefaultEntryAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	149	30	121	71	30	30	1461	931	S1" );
            }
        }
        S1_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            if( !this.bHandled ){
                this.nSourceState = MainStmTop.S1;
                this.DefaultDoingAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	149	30	121	71	30	30	1461	931	S1" );
                switch( nEventId ){ /* transition.ext1st */
                case ContextImpl.E1:{
            this.BgnTrans( pContextImpl, MainStmTop.S2 ); /* trans_action.begin */
            this.EndTrans( pContextImpl );
            bResult ||= true;
                } break; /* transition.extnxt */
                case ContextImpl.E2:{
            if (pContextImpl.internalAttribute == 0) { /* branch.ext1st */
                this.BgnTrans( pContextImpl, MainStmTop.S2 ); /* trans_action.begin */
                this.EndTrans( pContextImpl );
                bResult ||= true;
            } else { /* branch.begin */
                if (pContextImpl.internalAttribute == 1) { /* branch.ext1st */
                    this.BgnTrans( pContextImpl, MainStmTop.S6 ); /* trans_action.begin */
                    ( this.pMain as MainStmTop ).S6Hsm.Reset( pContextImpl, { entryPt: SubStmTop.Entry1, lastEnteredStateRecovering: ( this.pMain as MainStmTop ).lastEnteredStateRecovering } ); /* substm.begin */
                    this.EndTrans( pContextImpl );
                    bResult ||= true;
                } else { /* branch.begin */
                    this.BgnTrans( pContextImpl, MainStmTop.S7 ); /* trans_action.begin */
                    this.EndTrans( pContextImpl );
                    bResult ||= true;
                } /* branch.end */
            } /* branch.end */
                } break; /* transition.begin */
                default: break;
                }
            } /* transition.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.MainStm_EventProc( pContextImpl, nEventId, pEventParams );
        }
        S1_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( MainStmTop.S1 ) ){ 
                 this.DefaultExitAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	149	30	121	71	30	30	1461	931	S1" );
                this.MainStm_Exit( pContextImpl );
            }
        }
        S2_Entry( pContextImpl: ContextImpl ): void{ /* transition.name */
            if( this.Enterable( MainStmTop.S2 ) ){
                this.MainStm_Entry( pContextImpl );
                this.DefaultEntryAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	429	30	740	247	30	30	1461	931	S2" );
        if( !( this.pMain as MainStmTop ).lastEnteredStateRecovering && this.nTargetState == MainStmTop.S2 ){ /* state_action.name */
            this.nPseudostate = MainStmTop.S2Init;
        }
            }
        }
        S2_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            if( !this.bHandled ){
                this.nSourceState = MainStmTop.S2;
                this.DefaultDoingAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	429	30	740	247	30	30	1461	931	S2" );
                switch( nEventId ){ /* transition.ext1st */
                case ContextImpl.E4:{
            this.BgnTrans( pContextImpl, MainStmTop.S6 ); /* trans_action.begin */
            this.EndTrans( pContextImpl );
            bResult ||= true;
                } break; /* transition.extnxt */
                case ContextImpl.E2:{
            this.BgnTrans( pContextImpl, MainStmTop.S3 ); /* trans_action.begin */
            this.EndTrans( pContextImpl );
            bResult ||= true;
                } break; /* transition.begin */
                default: break;
                }
            } /* transition.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.MainStm_EventProc( pContextImpl, nEventId, pEventParams );
        }
        S2_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( MainStmTop.S2 ) ){ 
                 this.DefaultExitAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	429	30	740	247	30	30	1461	931	S2" );
                this.MainStm_Exit( pContextImpl );
            }
        }
        S21_Entry( pContextImpl: ContextImpl ): void{ /* transition.name */
            if( this.Enterable( MainStmTop.S21 ) ){
                this.S2_Entry( pContextImpl );
                this.DefaultEntryAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	199	60	120	81	30	30	1461	931	S21" );
        ( this.pMain as MainStmTop ).S2ShallowHist = MainStmTop.S21; /* history.extnxt */
            }
        }
        S21_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            if( !this.bHandled ){
                this.nSourceState = MainStmTop.S21;
                this.DefaultDoingAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	199	60	120	81	30	30	1461	931	S21" );
                switch( nEventId ){ /* transition.ext1st */
                case ContextImpl.E2:{
            this.BgnTrans( pContextImpl, MainStmTop.S22 ); /* trans_action.begin */
            this.EndTrans( pContextImpl );
            bResult ||= true;
                } break; /* transition.extnxt */
                case ContextImpl.E1:{
            this.BgnTrans( pContextImpl, MainStmTop.S3 ); /* trans_action.begin */
            this.EndTrans( pContextImpl );
            bResult ||= true;
                } break; /* transition.begin */
                default: break;
                }
            } /* transition.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.S2_EventProc( pContextImpl, nEventId, pEventParams );
        }
        S21_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( MainStmTop.S21 ) ){ 
                 this.DefaultExitAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	199	60	120	81	30	30	1461	931	S21" );
                this.S2_Exit( pContextImpl );
            }
        }
        S22_Entry( pContextImpl: ContextImpl ): void{ /* transition.name */
            if( this.Enterable( MainStmTop.S22 ) ){
                this.S2_Entry( pContextImpl );
                this.DefaultEntryAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	419	60	121	81	30	30	1461	931	S22" );
        ( this.pMain as MainStmTop ).S2ShallowHist = MainStmTop.S22; /* history.extnxt */
            }
        }
        S22_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            if( !this.bHandled ){
                this.nSourceState = MainStmTop.S22;
                this.DefaultDoingAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	419	60	121	81	30	30	1461	931	S22" );
                switch( nEventId ){ /* transition.ext1st */
                case ContextImpl.E0:{
            ( this.pMain as MainStmTop ).S2ShallowHist = StateMachine.STATE_UNDEF; /* history.end */
            this.BgnTrans( pContextImpl, MainStmTop.MainStm ); /* trans_action.begin */
            this.EndTrans( pContextImpl );
            bResult ||= true;
                } break; /* transition.begin */
                default: break;
                }
            } /* transition.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.S2_EventProc( pContextImpl, nEventId, pEventParams );
        }
        S22_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( MainStmTop.S22 ) ){ 
                 this.DefaultExitAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	419	60	121	81	30	30	1461	931	S22" );
                this.S2_Exit( pContextImpl );
            }
        }
        S8_Entry( pContextImpl: ContextImpl ): void{ /* transition.name */
            if( this.Enterable( MainStmTop.S8 ) ){
                this.MainStm_Entry( pContextImpl );
                this.DefaultEntryAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	429	550	741	268	30	30	1461	931	S8" );
        if( !( this.pMain as MainStmTop ).lastEnteredStateRecovering && this.nTargetState == MainStmTop.S8 ){ /* state_action.name */
            this.nPseudostate = MainStmTop.S81Init;
        }
        ( this.pMain as MainStmTop ).S8Rgn1Hsm.Reset( pContextImpl ); /* state_action.begin */
            }
        }
        S8_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            this.bHandled ||= ( this.pMain as MainStmTop ).S8Rgn1Hsm.EventProc( pContextImpl, nEventId, pEventParams ); /* stm_api.ext1st */
            if( !this.bHandled ){
                this.nSourceState = MainStmTop.S8;
                this.DefaultDoingAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	429	550	741	268	30	30	1461	931	S8" );
                switch( nEventId ){ /* transition.ext1st */
                case ContextImpl.E3:{
            if( ( this.pMain as MainStmTop ).S2ShallowHist != StateMachine.STATE_UNDEF ){ /* history.begin */
                this.BgnTrans( pContextImpl, ( this.pMain as MainStmTop ).S2ShallowHist );
                this.EndTrans( pContextImpl );
                bResult ||= true;
            }else{
                this.BgnTrans( pContextImpl, MainStmTop.MainStm ); /* trans_action.begin */
                this.EndTrans( pContextImpl );
                bResult ||= true;
            }
                } break; /* transition.extnxt */
                case ContextImpl.E5:{
            this.BgnTrans( pContextImpl, MainStmTop.S7 ); /* trans_action.begin */
            this.EndTrans( pContextImpl );
            bResult ||= true;
                } break; /* transition.begin */
                default: break;
                }
            } /* transition.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.MainStm_EventProc( pContextImpl, nEventId, pEventParams );
        }
        S8_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( MainStmTop.S8 ) ){ 
        ( this.pMain as MainStmTop ).S8Rgn1Hsm.Abort( pContextImpl ); /* state_action.end */
                 this.DefaultExitAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	429	550	741	268	30	30	1461	931	S8" );
                this.MainStm_Exit( pContextImpl );
            }
        }
        S811_Entry( pContextImpl: ContextImpl ): void{ /* transition.name */
            if( this.Enterable( MainStmTop.S811 ) ){
                this.S8_Entry( pContextImpl );
                this.DefaultEntryAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	119	20	121	81	30	30	1461	931	S811" );
            }
        }
        S811_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            if( !this.bHandled ){
                this.nSourceState = MainStmTop.S811;
                this.DefaultDoingAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	119	20	121	81	30	30	1461	931	S811" );
            } /* transition.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.S8_EventProc( pContextImpl, nEventId, pEventParams );
        }
        S811_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( MainStmTop.S811 ) ){ 
                 this.DefaultExitAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	119	20	121	81	30	30	1461	931	S811" );
                this.S8_Exit( pContextImpl );
            }
        }
        S812_Entry( pContextImpl: ContextImpl ): void{ /* transition.name */
            if( this.Enterable( MainStmTop.S812 ) ){
                this.S8_Entry( pContextImpl );
                this.DefaultEntryAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	479	20	121	81	30	30	1461	931	S812" );
            }
        }
        S812_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            if( !this.bHandled ){
                this.nSourceState = MainStmTop.S812;
                this.DefaultDoingAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	479	20	121	81	30	30	1461	931	S812" );
            } /* transition.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.S8_EventProc( pContextImpl, nEventId, pEventParams );
        }
        S812_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( MainStmTop.S812 ) ){ 
                 this.DefaultExitAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	479	20	121	81	30	30	1461	931	S812" );
                this.S8_Exit( pContextImpl );
            }
        }
        S7_Entry( pContextImpl: ContextImpl ): void{ /* transition.name */
            if( this.Enterable( MainStmTop.S7 ) ){
                this.MainStm_Entry( pContextImpl );
                this.DefaultEntryAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	69	430	281	441	30	30	1461	931	S7" );
        if( !( this.pMain as MainStmTop ).lastEnteredStateRecovering && this.nTargetState == MainStmTop.S7 ){ /* state_action.name */
            this.nPseudostate = MainStmTop.S7Init;
        }
            }
        }
        S7_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            if( !this.bHandled ){
                this.nSourceState = MainStmTop.S7;
                this.DefaultDoingAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	69	430	281	441	30	30	1461	931	S7" );
                switch( nEventId ){ /* transition.ext1st */
                case ContextImpl.E2:{
            this.BgnTrans( pContextImpl, MainStmTop.S72 ); /* trans_action.begin */
            this.EndTrans( pContextImpl );
            bResult ||= true;
                } break; /* transition.extnxt */
                case ContextImpl.E1:{
            this.bIsExternTrans = true; /* state_action.ext1st */
            this.BgnTrans( pContextImpl, MainStmTop.S71 ); /* trans_action.begin */
            this.EndTrans( pContextImpl );
            bResult ||= true;
                } break; /* transition.begin */
                default: break;
                }
            } /* transition.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.MainStm_EventProc( pContextImpl, nEventId, pEventParams );
        }
        S7_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( MainStmTop.S7 ) ){ 
        ( this.pMain as MainStmTop ).S7DeepHist = this.lastEnteredState; /* deep_hist.extnxt */
                 this.DefaultExitAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	69	430	281	441	30	30	1461	931	S7" );
                this.MainStm_Exit( pContextImpl );
            }
        }
        S71_Entry( pContextImpl: ContextImpl ): void{ /* transition.name */
            if( this.Enterable( MainStmTop.S71 ) ){
                this.S7_Entry( pContextImpl );
                this.DefaultEntryAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	19	60	241	241	30	30	1461	931	S71" );
        if( !( this.pMain as MainStmTop ).lastEnteredStateRecovering && this.nTargetState == MainStmTop.S71 ){ /* state_action.name */
            this.nPseudostate = MainStmTop.S711Init;
        }
        ( this.pMain as MainStmTop ).S71Rgn1Hsm.Reset( pContextImpl ); /* state_action.begin */
            }
        }
        S71_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            this.bHandled ||= ( this.pMain as MainStmTop ).S71Rgn1Hsm.EventProc( pContextImpl, nEventId, pEventParams ); /* stm_api.ext1st */
            if( !this.bHandled ){
                this.nSourceState = MainStmTop.S71;
                this.DefaultDoingAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	19	60	241	241	30	30	1461	931	S71" );
            } /* transition.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.S7_EventProc( pContextImpl, nEventId, pEventParams );
        }
        S71_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( MainStmTop.S71 ) ){ 
        ( this.pMain as MainStmTop ).S71Rgn1Hsm.Abort( pContextImpl ); /* state_action.end */
                 this.DefaultExitAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	19	60	241	241	30	30	1461	931	S71" );
                this.S7_Exit( pContextImpl );
            }
        }
        S7111_Entry( pContextImpl: ContextImpl ): void{ /* transition.name */
            if( this.Enterable( MainStmTop.S7111 ) ){
                this.S71_Entry( pContextImpl );
                this.DefaultEntryAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	19	40	81	61	30	30	1461	931	S7111" );
            }
        }
        S7111_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            if( !this.bHandled ){
                this.nSourceState = MainStmTop.S7111;
                this.DefaultDoingAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	19	40	81	61	30	30	1461	931	S7111" );
                switch( nEventId ){ /* transition.ext1st */
                case ContextImpl.E0:{
            this.BgnTrans( pContextImpl, MainStmTop.S7112 ); /* trans_action.begin */
            this.EndTrans( pContextImpl );
            bResult ||= true;
                } break; /* transition.begin */
                default: break;
                }
            } /* transition.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.S71_EventProc( pContextImpl, nEventId, pEventParams );
        }
        S7111_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( MainStmTop.S7111 ) ){ 
                 this.DefaultExitAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	19	40	81	61	30	30	1461	931	S7111" );
                this.S71_Exit( pContextImpl );
            }
        }
        S7112_Entry( pContextImpl: ContextImpl ): void{ /* transition.name */
            if( this.Enterable( MainStmTop.S7112 ) ){
                this.S71_Entry( pContextImpl );
                this.DefaultEntryAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	19	140	81	61	30	30	1461	931	S7112" );
            }
        }
        S7112_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            if( !this.bHandled ){
                this.nSourceState = MainStmTop.S7112;
                this.DefaultDoingAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	19	140	81	61	30	30	1461	931	S7112" );
            } /* transition.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.S71_EventProc( pContextImpl, nEventId, pEventParams );
        }
        S7112_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( MainStmTop.S7112 ) ){ 
                 this.DefaultExitAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	19	140	81	61	30	30	1461	931	S7112" );
                this.S71_Exit( pContextImpl );
            }
        }
        S72_Entry( pContextImpl: ContextImpl ): void{ /* transition.name */
            if( this.Enterable( MainStmTop.S72 ) ){
                this.S7_Entry( pContextImpl );
                this.DefaultEntryAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	79	340	121	61	30	30	1461	931	S72" );
            }
        }
        S72_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            if( !this.bHandled ){
                this.nSourceState = MainStmTop.S72;
                this.DefaultDoingAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	79	340	121	61	30	30	1461	931	S72" );
            } /* transition.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.S7_EventProc( pContextImpl, nEventId, pEventParams );
        }
        S72_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( MainStmTop.S72 ) ){ 
                 this.DefaultExitAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	79	340	121	61	30	30	1461	931	S72" );
                this.S7_Exit( pContextImpl );
            }
        }
        S6_Entry( pContextImpl: ContextImpl ): void{ /* transition.name */
            if( this.Enterable( MainStmTop.S6 ) ){
                this.MainStm_Entry( pContextImpl );
                this.DefaultEntryAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	1242	330	128	81	30	30	1461	931	S6" );
        ( this.pMain as MainStmTop ).S6Hsm.Reset( pContextImpl ); /* state_action.begin */
            }
        }
        S6_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
    this.bHandled ||= ( this.pMain as MainStmTop ).S6Hsm.EventProc( pContextImpl, nEventId, pEventParams ); /* stm_api.extnxt */
            if( !this.bHandled ){
                this.nSourceState = MainStmTop.S6;
                this.DefaultDoingAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	1242	330	128	81	30	30	1461	931	S6" );
            } /* transition.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.MainStm_EventProc( pContextImpl, nEventId, pEventParams );
        }
        S6_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( MainStmTop.S6 ) ){ 
        ( this.pMain as MainStmTop ).S6Hsm.Abort( pContextImpl ); /* state_action.end */
                 this.DefaultExitAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	1242	330	128	81	30	30	1461	931	S6" );
                this.MainStm_Exit( pContextImpl );
            }
        }
        S3_Entry( pContextImpl: ContextImpl ): void{ /* transition.name */
            if( this.Enterable( MainStmTop.S3 ) ){
                this.MainStm_Entry( pContextImpl );
                this.DefaultEntryAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	1269	50	121	81	30	30	1461	931	S3" );
            }
        }
        S3_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            if( !this.bHandled ){
                this.nSourceState = MainStmTop.S3;
                this.DefaultDoingAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	1269	50	121	81	30	30	1461	931	S3" );
                switch( nEventId ){ /* transition.ext1st */
                case ContextImpl.E0:{
            this.BgnTrans( pContextImpl, MainStmTop.S6 ); /* trans_action.begin */
            this.EndTrans( pContextImpl );
            bResult ||= true;
                } break; /* transition.begin */
                default: break;
                }
            } /* transition.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.MainStm_EventProc( pContextImpl, nEventId, pEventParams );
        }
        S3_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( MainStmTop.S3 ) ){ 
                 this.DefaultExitAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	1269	50	121	81	30	30	1461	931	S3" );
                this.MainStm_Exit( pContextImpl );
            }
        }
        S9_Entry( pContextImpl: ContextImpl ): void{ /* transition.name */
            if( this.Enterable( MainStmTop.S9 ) ){
                this.MainStm_Entry( pContextImpl );
                this.DefaultEntryAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	1249	450	121	81	30	30	1461	931	S9" );
        ( this.pMain as MainStmTop ).S9Hsm.Reset( pContextImpl ); /* state_action.begin */
            }
        }
        S9_EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
    this.bHandled ||= ( this.pMain as MainStmTop ).S9Hsm.EventProc( pContextImpl, nEventId, pEventParams ); /* stm_api.extnxt */
            if( !this.bHandled ){
                this.nSourceState = MainStmTop.S9;
                this.DefaultDoingAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	1249	450	121	81	30	30	1461	931	S9" );
            } /* transition.end */
            this.bHandled ||= bResult;
            this.wasHandled ||= bResult;
            return this.MainStm_EventProc( pContextImpl, nEventId, pEventParams );
        }
        S9_Exit( pContextImpl: ContextImpl ): void{
            if( this.Exitable( MainStmTop.S9 ) ){ 
        ( this.pMain as MainStmTop ).S9Hsm.Abort( pContextImpl ); /* state_action.end */
                 this.DefaultExitAction( pContextImpl, "AllNotations/JavaSample00/Model/ContextImpl/MainStm/	1249	450	121	81	30	30	1461	931	S9" );
                this.MainStm_Exit( pContextImpl );
            }
        }
        BgnTrans( pContextImpl: ContextImpl, targetState: long ): void{ /* state_exit.name */
            this.nTargetState = targetState;
            this.nPseudostate = targetState;
            if( this.nCurrentState == MainStmTop.MainStm ) { this.MainStm_Exit( pContextImpl ); } /* state_exit.ext1st */
            else if( this.nCurrentState == MainStmTop.S1 ) { this.S1_Exit( pContextImpl ); } /* state_exit.extnxt */
            else if( this.nCurrentState == MainStmTop.S21 ) { this.S21_Exit( pContextImpl ); } /* state_exit.extnxt */
            else if( this.nCurrentState == MainStmTop.S22 ) { this.S22_Exit( pContextImpl ); } /* state_exit.extnxt */
            else if( this.nCurrentState == MainStmTop.S2 ) { this.S2_Exit( pContextImpl ); } /* state_exit.extnxt */
            else if( this.nCurrentState == MainStmTop.S811 ) { this.S811_Exit( pContextImpl ); } /* state_exit.extnxt */
            else if( this.nCurrentState == MainStmTop.S812 ) { this.S812_Exit( pContextImpl ); } /* state_exit.extnxt */
            else if( this.nCurrentState == MainStmTop.S8 ) { this.S8_Exit( pContextImpl ); } /* state_exit.extnxt */
            else if( this.nCurrentState == MainStmTop.S7111 ) { this.S7111_Exit( pContextImpl ); } /* state_exit.extnxt */
            else if( this.nCurrentState == MainStmTop.S7112 ) { this.S7112_Exit( pContextImpl ); } /* state_exit.extnxt */
            else if( this.nCurrentState == MainStmTop.S71 ) { this.S71_Exit( pContextImpl ); } /* state_exit.extnxt */
            else if( this.nCurrentState == MainStmTop.S72 ) { this.S72_Exit( pContextImpl ); } /* state_exit.extnxt */
            else if( this.nCurrentState == MainStmTop.S7 ) { this.S7_Exit( pContextImpl ); } /* state_exit.extnxt */
            else if( this.nCurrentState == MainStmTop.S6 ) { this.S6_Exit( pContextImpl ); } /* state_exit.extnxt */
            else if( this.nCurrentState == MainStmTop.S3 ) { this.S3_Exit( pContextImpl ); } /* state_exit.extnxt */
            else if( this.nCurrentState == MainStmTop.S9 ) { this.S9_Exit( pContextImpl ); } /* state_exit.extnxt */
            else {} /* state_exit.begin */
        } /* state_exit.end */
        public Reset( pContextImpl: ContextImpl, args: ResetArgs = {} ): boolean { /* state_impl.name */
            const entryPt = args.entryPt ?? StateMachine.STATE_UNDEF;
            const lastEnteredStateRecovering = args.lastEnteredStateRecovering ?? false;
            if( entryPt != StateMachine.STATE_UNDEF ){
                this.Req( entryPt );
                return false;
            }
            this.nPseudostate = MainStmTop.MainStm;
            this.bIsExternTrans = true;
            this.BgnTrans( pContextImpl, this.nPseudostate );
            this.EndTrans( pContextImpl );
            return true;
        }
        public EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{
            let bResult: boolean = false;
            this.nLCAState = StateMachine.STATE_UNDEF;
            this.bHandled = false;
            this.wasHandled = false;
            if( this.nCurrentState == MainStmTop.MainStm ) { this.MainStm_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.ext1st */
            else if( this.nCurrentState == MainStmTop.S1 ) { this.S1_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.extnxt */
            else if( this.nCurrentState == MainStmTop.S21 ) { this.S21_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.extnxt */
            else if( this.nCurrentState == MainStmTop.S22 ) { this.S22_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.extnxt */
            else if( this.nCurrentState == MainStmTop.S2 ) { this.S2_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.extnxt */
            else if( this.nCurrentState == MainStmTop.S811 ) { this.S811_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.extnxt */
            else if( this.nCurrentState == MainStmTop.S812 ) { this.S812_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.extnxt */
            else if( this.nCurrentState == MainStmTop.S8 ) { this.S8_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.extnxt */
            else if( this.nCurrentState == MainStmTop.S7111 ) { this.S7111_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.extnxt */
            else if( this.nCurrentState == MainStmTop.S7112 ) { this.S7112_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.extnxt */
            else if( this.nCurrentState == MainStmTop.S71 ) { this.S71_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.extnxt */
            else if( this.nCurrentState == MainStmTop.S72 ) { this.S72_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.extnxt */
            else if( this.nCurrentState == MainStmTop.S7 ) { this.S7_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.extnxt */
            else if( this.nCurrentState == MainStmTop.S6 ) { this.S6_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.extnxt */
            else if( this.nCurrentState == MainStmTop.S3 ) { this.S3_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.extnxt */
            else if( this.nCurrentState == MainStmTop.S9 ) { this.S9_EventProc( pContextImpl, nEventId, pEventParams ); } /* state_impl.extnxt */
            else {} /* state_impl.begin */
            return bResult; /* state_impl.end */
        }
        Abort( pContextImpl: ContextImpl ): boolean {
            this.nSourceState = MainStmTop.MainStm;
            this.BgnTrans( pContextImpl, StateMachine.STATE_UNDEF );
            this.EndTrans( pContextImpl );
            return true;
        }
        EndTrans( pContextImpl: ContextImpl ): void{ /* state_entry.name */
            this.nCurrentState = this.nTargetState;
            this.bIsExternTrans = false;
            if( this.nCurrentState == MainStmTop.MainStm ) { this.MainStm_Entry( pContextImpl ); } /* state_entry.ext1st */
            else if( this.nCurrentState == MainStmTop.S1 ) { this.S1_Entry( pContextImpl ); } /* state_entry.extnxt */
            else if( this.nCurrentState == MainStmTop.S21 ) { this.S21_Entry( pContextImpl ); } /* state_entry.extnxt */
            else if( this.nCurrentState == MainStmTop.S22 ) { this.S22_Entry( pContextImpl ); } /* state_entry.extnxt */
            else if( this.nCurrentState == MainStmTop.S2 ) { this.S2_Entry( pContextImpl ); } /* state_entry.extnxt */
            else if( this.nCurrentState == MainStmTop.S811 ) { this.S811_Entry( pContextImpl ); } /* state_entry.extnxt */
            else if( this.nCurrentState == MainStmTop.S812 ) { this.S812_Entry( pContextImpl ); } /* state_entry.extnxt */
            else if( this.nCurrentState == MainStmTop.S8 ) { this.S8_Entry( pContextImpl ); } /* state_entry.extnxt */
            else if( this.nCurrentState == MainStmTop.S7111 ) { this.S7111_Entry( pContextImpl ); } /* state_entry.extnxt */
            else if( this.nCurrentState == MainStmTop.S7112 ) { this.S7112_Entry( pContextImpl ); } /* state_entry.extnxt */
            else if( this.nCurrentState == MainStmTop.S71 ) { this.S71_Entry( pContextImpl ); } /* state_entry.extnxt */
            else if( this.nCurrentState == MainStmTop.S72 ) { this.S72_Entry( pContextImpl ); } /* state_entry.extnxt */
            else if( this.nCurrentState == MainStmTop.S7 ) { this.S7_Entry( pContextImpl ); } /* state_entry.extnxt */
            else if( this.nCurrentState == MainStmTop.S6 ) { this.S6_Entry( pContextImpl ); } /* state_entry.extnxt */
            else if( this.nCurrentState == MainStmTop.S3 ) { this.S3_Entry( pContextImpl ); } /* state_entry.extnxt */
            else if( this.nCurrentState == MainStmTop.S9 ) { this.S9_Entry( pContextImpl ); } /* state_entry.extnxt */
            else {} /* state_entry.begin */
        } /* state_entry.end */
        StateDefaultTrans( pContextImpl: ContextImpl ): boolean{ /* default_trans.name */
            let bResult: boolean = false;
            this.nSourceState = this.nCurrentState;
            this.nLCAState = StateMachine.STATE_UNDEF;
        if ( this.nPseudostate == MainStmTop.MainStmInit  ) { /* branch.ext1st */
            this.BgnTrans( pContextImpl, MainStmTop.S1 ); /* trans_action.begin */
            this.EndTrans( pContextImpl );
            bResult ||= true;
        } else if ( this.nCurrentState == MainStmTop.S6 && this.nPseudostate == SubStmTop.Exit1  ) { /* branch.extnxt */
            this.BgnTrans( pContextImpl, MainStmTop.S9 ); /* trans_action.begin */
            this.EndTrans( pContextImpl );
            bResult ||= true;
        } else if ( this.nCurrentState == MainStmTop.S9 && this.nPseudostate == MainStmTop.S9  /* substm.extnxt */
         && ( this.pMain as MainStmTop ).S9Hsm.IsFinished()  /* default_trans.extnxt */) { /* branch.extnxt */
            this.BgnTrans( pContextImpl, MainStmTop.S812 ); /* trans_action.begin */
            ( this.pMain as MainStmTop ).S8Rgn1Hsm.Reset( pContextImpl, { entryPt: MainStmTop.S821 } ); /* region.begin */
            this.EndTrans( pContextImpl );
            bResult ||= true;
        } else if ( this.nPseudostate == MainStmTop.S2Init  ) { /* branch.extnxt */
            this.BgnTrans( pContextImpl, MainStmTop.S21 ); /* trans_action.begin */
            this.EndTrans( pContextImpl );
            bResult ||= true;
        } else if ( this.nPseudostate == MainStmTop.S81Init  ) { /* branch.extnxt */
            this.BgnTrans( pContextImpl, MainStmTop.S811 ); /* trans_action.begin */
            this.EndTrans( pContextImpl );
            bResult ||= true;
        } else if ( this.nPseudostate == MainStmTop.S711Init  ) { /* branch.extnxt */
            this.BgnTrans( pContextImpl, MainStmTop.S7111 ); /* trans_action.begin */
            this.EndTrans( pContextImpl );
            bResult ||= true;
        } else if ( this.nPseudostate == MainStmTop.S7Init  ) { /* branch.extnxt */
            if( ( this.pMain as MainStmTop ).S7DeepHist != StateMachine.STATE_UNDEF ){ /* deep_hist.begin */
                this.BgnTrans( pContextImpl, ( this.pMain as MainStmTop ).S7DeepHist );
                ( this.pMain as MainStmTop ).lastEnteredStateRecovering = true;
                this.EndTrans( pContextImpl );
                bResult ||= true;
            }else{
                this.BgnTrans( pContextImpl, MainStmTop.S71 ); /* trans_action.begin */
                this.EndTrans( pContextImpl );
                bResult ||= true;
            }
            }else if( this.nCurrentState != this.nPseudostate ){ /* default_trans.begin */
                this.BgnTrans( pContextImpl, this.nPseudostate );
                this.EndTrans( pContextImpl );
                bResult = true;
            }else{
            }
            this.bHandled ||= bResult; /* default_trans.end */
            this.wasHandled ||= bResult;
            ( this.pMain as MainStmTop ).lastEnteredStateRecovering = false;
            return bResult;
        }
}
class SubStmTop extends BaseStmTop { /* statemachine.begin */
        public pParentStm: StateMachine | undefined;
        public lastEnteredStateRecovering: boolean = false;
/* states' declaration */ /* state_decl.begin */
        public static readonly S101: long        = ( 1 <<  0 ); /* state_decl.name */
        public static readonly SubStmInit: long  = ( 1 <<  1 ); /* state_decl.name */
        public static readonly S102: long        = ( 1 <<  2 ); /* state_decl.name */
        public static readonly Entry1: long      = ( 1 <<  3 ); /* state_decl.name */
        public static readonly Exit1: long       = ( 1 <<  4 ); /* state_decl.name */
        public static readonly SubStm: long      = ( SubStmTop.S101 /* state_decl.ext1st */ | SubStmTop.SubStmInit /* state_decl.extnxt */ | SubStmTop.S102 /* state_decl.extnxt */ | SubStmTop.Entry1 /* state_decl.extnxt */ | SubStmTop.Exit1 /* state_decl.extnxt */ ); /* state_decl.end */
        SubStmHsm: _SubStmTop = new _SubStmTop();                /* region.name */

        public EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{ /* stm_api.name */
            return this.SubStmHsm.EventProc( pContextImpl, nEventId, pEventParams );
        }
        public StateDefaultTrans( pContextImpl: ContextImpl ): boolean{
            let bResult: boolean;
            while( true ){
                bResult = false;
                bResult ||= this.SubStmHsm.StateDefaultTrans( pContextImpl ); /* stm_api.begin */
                if( bResult == false ){
                    break;
                }
            }
            return bResult;
        }
        public Reset( pContextImpl: ContextImpl, args: ResetArgs = {}): boolean {
            this.SubStmHsm.Abort( pContextImpl );
            return this.SubStmHsm.Reset( pContextImpl, { entryPt: args.entryPt ?? StateMachine.STATE_UNDEF,
                lastEnteredStateRecovering: args.lastEnteredStateRecovering ?? false } );
        }
        public Abort( pContextImpl: ContextImpl ): boolean{
            return this.SubStmHsm.Abort( pContextImpl );
        }
        public IsFinished(): boolean{
            return this.SubStmHsm.nPseudostate == SubStmTop.SubStm;
        }
 /* statemachine.end */
        public Prepare( pParent: StateMachine | undefined ): void{
            this.pParentStm = pParent;
            this.SubStmHsm.pMain = this; /* region.ext1st */
        }
} /* SubStmTop */
class MainStmTop extends BaseStmTop { /* statemachine.begin */
        public pParentStm: StateMachine | undefined;
        public lastEnteredStateRecovering: boolean = false;
/* states' declaration */ /* state_decl.begin */
        public static readonly S821: long        = ( 1 <<  0 ); /* state_decl.name */
        public static readonly S82Init: long     = ( 1 <<  1 ); /* state_decl.name */
        public static readonly S822: long        = ( 1 <<  2 ); /* state_decl.name */
        public static readonly S8Rgn1: long      = ( MainStmTop.S821 /* state_decl.ext1st */ | MainStmTop.S82Init /* state_decl.extnxt */ | MainStmTop.S822 /* state_decl.extnxt */ ); /* state_decl.end */
/* states' declaration */ /* state_decl.begin */
        public static readonly S7121: long       = ( 1 <<  0 ); /* state_decl.name */
        public static readonly S7122: long       = ( 1 <<  1 ); /* state_decl.name */
        public static readonly S712Init: long    = ( 1 <<  2 ); /* state_decl.name */
        public static readonly S71Rgn1: long     = ( MainStmTop.S7121 /* state_decl.ext1st */ | MainStmTop.S7122 /* state_decl.extnxt */ | MainStmTop.S712Init /* state_decl.extnxt */ ); /* state_decl.end */
/* states' declaration */ /* state_decl.begin */
        public static readonly S1: long          = ( 1 <<  0 ); /* state_decl.name */
        public static readonly MainStmInit: long  = ( 1 <<  1 ); /* state_decl.name */
        public static readonly S21: long         = ( 1 <<  2 ); /* state_decl.name */
        public static readonly S22: long         = ( 1 <<  3 ); /* state_decl.name */
        public static readonly S2Init: long      = ( 1 <<  4 ); /* state_decl.name */
        public static readonly S2: long          = ( MainStmTop.S21 /* state_decl.ext1st */ | MainStmTop.S22 /* state_decl.extnxt */ | MainStmTop.S2Init /* state_decl.extnxt */ ); /* state_decl.end */
        public static readonly S811: long        = ( 1 <<  5 ); /* state_decl.name */
        public static readonly S81Init: long     = ( 1 <<  6 ); /* state_decl.name */
        public static readonly S812: long        = ( 1 <<  7 ); /* state_decl.name */
        public static readonly S8: long          = ( MainStmTop.S811 /* state_decl.ext1st */ | MainStmTop.S81Init /* state_decl.extnxt */ | MainStmTop.S812 /* state_decl.extnxt */ ); /* state_decl.end */
        public static readonly S7111: long       = ( 1 <<  8 ); /* state_decl.name */
        public static readonly S7112: long       = ( 1 <<  9 ); /* state_decl.name */
        public static readonly S711Init: long    = ( 1 << 10 ); /* state_decl.name */
        public static readonly S71: long         = ( MainStmTop.S7111 /* state_decl.ext1st */ | MainStmTop.S7112 /* state_decl.extnxt */ | MainStmTop.S711Init /* state_decl.extnxt */ ); /* state_decl.end */
        public static readonly S7Init: long      = ( 1 << 11 ); /* state_decl.name */
        public static readonly S72: long         = ( 1 << 12 ); /* state_decl.name */
        public static readonly S7: long          = ( MainStmTop.S71 /* state_decl.ext1st */ | MainStmTop.S7Init /* state_decl.extnxt */ | MainStmTop.S72 /* state_decl.extnxt */ ); /* state_decl.end */
        public static readonly S6: long          = ( 1 << 13 ); /* state_decl.name */
        public static readonly S3: long          = ( 1 << 14 ); /* state_decl.name */
        public static readonly S9: long          = ( 1 << 15 ); /* state_decl.name */
        public static readonly MainStm: long     = ( MainStmTop.S1 /* state_decl.ext1st */ | MainStmTop.MainStmInit /* state_decl.extnxt */ | MainStmTop.S2 /* state_decl.extnxt */ | MainStmTop.S8 /* state_decl.extnxt */ | MainStmTop.S7 /* state_decl.extnxt */ | MainStmTop.S6 /* state_decl.extnxt */ | MainStmTop.S3 /* state_decl.extnxt */ | MainStmTop.S9 /* state_decl.extnxt */ ); /* state_decl.end */
        MainStmHsm: _MainStmTop = new _MainStmTop();             /* region.name */
        S2ShallowHist: long = StateMachine.STATE_UNDEF; /* history.name */
        S8Rgn1Hsm: _S8Rgn1Hsm = new _S8Rgn1Hsm();                /* region.name */
        S71Rgn1Hsm: _S71Rgn1Hsm = new _S71Rgn1Hsm();             /* region.name */
        S7DeepHist: long = StateMachine.STATE_UNDEF; /* history.name */
    S6Hsm: SubStmTop = new SubStmTop();                          /* substm.name */
    S9Hsm: SubStmTop = new SubStmTop();                          /* substm.name */

        public EventProc( pContextImpl: ContextImpl, nEventId: number, pEventParams: EventParams ): boolean{ /* stm_api.name */
            return this.MainStmHsm.EventProc( pContextImpl, nEventId, pEventParams );
        }
        public StateDefaultTrans( pContextImpl: ContextImpl ): boolean{
            let bResult: boolean;
            while( true ){
                bResult = false;
                bResult ||= this.S8Rgn1Hsm.StateDefaultTrans( pContextImpl ); /* stm_api.begin */
                bResult ||= this.S71Rgn1Hsm.StateDefaultTrans( pContextImpl ); /* stm_api.begin */
                bResult ||= this.S6Hsm.StateDefaultTrans( pContextImpl ) /* stm_api.end */
                            || this.S9Hsm.StateDefaultTrans( pContextImpl ) /* stm_api.end */
                            || this.MainStmHsm.StateDefaultTrans( pContextImpl ); /* stm_api.begin */
                if( bResult == false ){
                    break;
                }
            }
            return bResult;
        }
        public Reset( pContextImpl: ContextImpl, args: ResetArgs = {}): boolean {
            this.MainStmHsm.Abort( pContextImpl );
            return this.MainStmHsm.Reset( pContextImpl, { entryPt: args.entryPt ?? StateMachine.STATE_UNDEF,
                lastEnteredStateRecovering: args.lastEnteredStateRecovering ?? false } );
        }
        public Abort( pContextImpl: ContextImpl ): boolean{
            return this.MainStmHsm.Abort( pContextImpl );
        }
        public IsFinished(): boolean{
            return this.MainStmHsm.nPseudostate == MainStmTop.MainStm;
        }
 /* statemachine.end */
        public Prepare( pParent: StateMachine | undefined ): void{
            this.pParentStm = pParent;
            this.MainStmHsm.pMain = this; /* region.ext1st */
            this.S2ShallowHist = StateMachine.STATE_UNDEF; /* history.ext1st */
            this.S8Rgn1Hsm.pMain = this; /* region.ext1st */
            this.S71Rgn1Hsm.pMain = this; /* region.ext1st */
            this.S7DeepHist = StateMachine.STATE_UNDEF; /* history.ext1st */
    this.S6Hsm.Prepare( this.MainStmHsm ); /* substm.ext1st */
    this.S9Hsm.Prepare( this.MainStmHsm ); /* substm.ext1st */
        }
} /* MainStmTop */
