/* File generated by Đức's ClasHStamP */
package design.interfaces;

import java.io.*;
import java.util.*;

public  interface Interface1
{
    public void finalMethod(
    );                                                                                  
}
