/* File generated by Đức's ClasHStamP */
import type { Integer, long, Boolean, String } from "#all_notations/java_sample00/stdtype/stdtype";

export class Interface2
{
    public methodWithParams(
        parm1: String,
        parm2: Integer
    ): void {
    } /* Interface2.methodWithParams */
    constructor(
    ){
    }                                                                                           
}
