/* File generated by Đức's ClasHStamP */
import type { Integer, long, Boolean, String } from "@all_notations/java_sample00/stdtype/stdtype";

export class Interface1
{
    public finalMethod(
    ): void {
    } /* Interface1.finalMethod */
    constructor(
    ){
    }                                                                                           
}
