/* File generated by Đức's ClasHStamP */
package design.base;

import java.io.*;
import java.util.*;

public  class EventParams
{
    public  EventParams(
    ){
    }                                                                                           
}
