/* File generated by Đức's ClasHStamP */
package all_notations.java_sample00.abstracts;

import java.io.*;
import java.util.*;

public  class BaseStmTop
{
    public  BaseStmTop(
    ){
    }                                                                                           
}
