/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package Base;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the class HdStateMachine
 * 
 * @author Acceleo 3 Example - UML to Java generator
 * @generated
 */
public class HdStateMachine {
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public HdStateMachine() {
		super();
	}
	/**
	 * The documentation of the method operation1.
	 * 
	 * @return
	 * 
	 * @generated
	 */
	public boolean operation1() {
		// Start of user code for the body of operation1
		// TODO should be implemented
		return null;
		// End of user code
	}
	
	
	
}
