/* File generated by Đức's ClasHStamP */
package all_notations.java_sample00.model;

import java.io.*;
import java.util.*;

public  class Composition
{
    public  Composition(
        Integer _attribute4
    ){
        attribute4 = _attribute4;
    }                                                                                           
    private Integer attribute4;                                 
}
