/* File generated by Đức's ClasHStamP */
package all_notations.java_sample00.model;

import java.io.*;
import java.util.*;
import all_notations.java_sample00.model.*;

public  class ContextImpl extends Context
{
    protected void protectedMethod(
    ){
    } /* ContextImpl.protectedMethod */

    protected static void checkE1Params(
        EventParams e
    ){
    } /* ContextImpl.checkE1Params */
    public  ContextImpl(
        Integer _derivableAttribute,
        String _publicAttribute,
        Integer _privateAttribute,
        Integer _internalAttribute,
        Integer _readOnlyAttribute,
        Aggregration[] _anAggregation,
        Composition[] _aProtectedComposition
    ) {
        super( _derivableAttribute, _publicAttribute, _privateAttribute, _internalAttribute, _readOnlyAttribute, _anAggregation, _aProtectedComposition );

    }                                                                                           
}
