/* File generated by Đức's ClasHStamP */
package all_notations.java_sample00.model;

import java.io.*;
import java.util.*;

public  class EventListener
{
    public  EventListener(
    ){
    }                                                                                           
}
