/* File generated by Đức's ClasHStamP */
import 'module-alias/register';
import 'source-map-support/register';
import type { Integer, long, Boolean, String, ResetArgs } from "@all_notations/java_sample00/stdtype/stdtype";

        export class AFriend
        {
            constructor(
                _attribute3: Integer
            ){
                this.attribute3 = _attribute3;
            }                                                                                   
            attribute3: Integer;                                
        }
