/* File generated by Đức's ClasHStamP */
import 'module-alias/register';
import 'source-map-support/register';
import type { Integer, long, Boolean, String, ResetArgs } from "@all_notations/java_sample00/stdtype/stdtype";

export class Aggregration
{
    constructor(
        _attribute2: Integer
    ){
        this.attribute2 = _attribute2;
    }                                                                                           
    private attribute2: Integer;                                
}
