/* File generated by Đức's ClasHStamP */
import 'module-alias/register';
import 'source-map-support/register';
import type { Integer, long, Boolean, String, ResetArgs } from "@all_notations/java_sample00/stdtype/stdtype";

        export class CalledDependency
        {
            constructor(
                _attribute0: Integer
            ){
                this.attribute0 = _attribute0;
            }                                                                                   
            private attribute0: Integer;                        
        }
