/* File generated by Đức's ClasHStamP */
import 'module-alias/register';
import 'source-map-support/register';
import type { Integer, long, Boolean, String, ResetArgs } from "@all_notations/java_sample00/stdtype/stdtype";

export class Composition
{
    constructor(
        _attribute4: Integer
    ){
        this.attribute4 = _attribute4;
    }                                                                                           
    private attribute4: Integer;                                
}
