/* File generated by Đức's ClasHStamP */
import 'module-alias/register';
import 'source-map-support/register';
import type { Integer, long, Boolean, String, ResetArgs } from "@all_notations/java_sample00/stdtype/stdtype";
import { BaseClass } from "@all_notations/java_sample00/abstracts/BaseClass";
import { Interface2 } from "@all_notations/java_sample00/interfaces/Interface2";
import { Interface1 } from "@all_notations/java_sample00/interfaces/Interface1";
import { Aggregration } from "@all_notations/java_sample00/model/Aggregration";
import { Composition } from "@all_notations/java_sample00/model/Composition";
import { UsedDependency } from "@all_notations/java_sample00/model/UsedDependency";

export class Context extends BaseClass implements Interface2, Interface1
{
    private static classOrStaticAttribute: Integer;             
    private static initializedStaticArray: Integer[] = [1, 2, 3];
    private static finalConstantAttribute: Integer = 5;         
    public staticclassOrStaticMethod(
    ): void {
    } /* Context.classOrStaticMethod */
    public publicMethod(
    ): void {
    } /* Context.publicMethod */

    private privateLeafMethod(
    ): void {
    } /* Context.privateLeafMethod */
    public methodWithParams(
        parm1: String,
        parm2: Integer
    ): void {
    } /* Context.methodWithParams */
    public methodReturnsSomething(
    ): UsedDependency {
		return new UsedDependency(0);
    } /* Context.methodReturnsSomething */
    public methodThrowsException(
    ): void {
    } /* Context.methodThrowsException */
    public finalMethod(
    ): void {
    } /* Context.finalMethod */
    protected protectedMethod(
    ): void {
    } /* Context.protectedMethod */

    protected packageVisibleMethod(
    ): void {
    } /* Context.packageVisibleMethod */

    constructor(
        _derivableAttribute: Integer,
        _publicAttribute: String,
        _privateAttribute: Integer,
        _internalAttribute: Integer,
        _readOnlyAttribute: Integer,
        _anAggregation: Aggregration[] | undefined,
        _aProtectedComposition: Composition[] | undefined
    ) {
        super( _derivableAttribute );

        this.publicAttribute = _publicAttribute;
        this.privateAttribute = _privateAttribute;
        this.internalAttribute = _internalAttribute;
        this.isInitializedAttribute = true;
        this.readOnlyAttribute = _readOnlyAttribute;
        this.anAggregation = _anAggregation;
        this.aProtectedComposition = _aProtectedComposition;
    }                                                                                           
    public publicAttribute: String;                             
    private privateAttribute: Integer;                          
    internalAttribute: Integer;                                 
    private isInitializedAttribute: Boolean;                    
    private readOnlyAttribute: Integer;                         
    private anAggregation: Aggregration[] | undefined;             
    protected aProtectedComposition: Composition[] | undefined;    
}
