/* File generated by Đức's ClasHStamP */
import 'module-alias/register';
import 'source-map-support/register';
import type { Integer, long, Boolean, String, ResetArgs } from "@all_notations/java_sample00/stdtype/stdtype";

export class UsedDependency
{
    constructor(
        _attribute6: Integer
    ){
        this.attribute6 = _attribute6;
    }                                                                                           
    private attribute6: Integer;                                
}
