/* File generated by Đức's ClasHStamP */
package design.abstracts;

import java.awt.Rectangle;

import java.io.*;
import java.util.*;

import design.base.StateMachine;
import simulator.ModelExecutor;

public  class BaseStmTop
{
    public StateMachine pParentStm = null;
    public boolean lastEnteredStateRecovering = false;
    public String dgrName = "";
    public String instanceName = "";
    
    public void Prepare( StateMachine pParent, String _dgrName, String _instanceName ){
        pParentStm = pParent;
        dgrName = _dgrName;
        instanceName = _instanceName;
        // Ensure a non-modal diagram window exists for this state machine
		ModelExecutor.getInstance().createWindow(instanceName, instanceName, "../AdasUml/image/" + _dgrName + ".PNG");        
	} /* StateMachine.Prepare */	
    
    public  BaseStmTop(
    ){
    }                                                                                           
}