/* File generated by Đức's ClasHStamP */
package design.abstracts;

import java.io.*;
import java.util.*;

public  class BaseClass
{
    public  void publicMethod(
    ){
    } /* BaseClass.publicMethod */
    protected void protectedMethod(
    ){
    } /* BaseClass.protectedMethod */

    protected void packageVisibleMethod(
    ){
    } /* BaseClass.packageVisibleMethod */

    public  BaseClass(
        Integer _derivableAttribute
    ){
        derivableAttribute = _derivableAttribute;
    }                                                                                           
    Integer derivableAttribute;                                 
}
