/* File generated by Đức's ClasHStamP */
package all_notations.java_sample00.base;

import java.io.*;
import java.util.*;
import all_notations.java_sample00.abstracts.*;

public  class StateMachine
{
    public static final long STATE_UNDEF = 0;                   
    public Boolean Enterable(
        long nThisState
    ){
        // BOOL isThisLCA = IS_IN( pHdStateMachine->nLCAState, nThisState );
        boolean isThisLCA = isIn(this.nLCAState, nThisState);

        // if( !isThisLCA || pHdStateMachine->nLCAState == STATE_UNDEF ){ return TRUE; }
        if (!isThisLCA || this.nLCAState == STATE_UNDEF) {
            return Boolean.TRUE;
        }
        return Boolean.FALSE;
    } /* StateMachine.Enterable */

    public Boolean Exitable(
        long nThisState
    ){
        // BOOL isThisLCA = IS_IN( pHdStateMachine->nSourceState, nThisState )
        //                   && IS_IN( pHdStateMachine->nTargetState, nThisState );
        boolean isThisLCA =
            isIn(this.nSourceState, nThisState) &&
            isIn(this.nTargetState, nThisState);

        // if( !isThisLCA || pHdStateMachine->bIsExternTrans ){ 
        //     pHdStateMachine->bIsExternTrans &= !isThisLCA;
        //     return TRUE;
        // } else { 
        //     pHdStateMachine->nLCAState = nThisState;
        // }
        // return FALSE;
        if (!isThisLCA || Boolean.TRUE.equals(this.bIsExternTrans)) {
            boolean current = Boolean.TRUE.equals(this.bIsExternTrans);
            this.bIsExternTrans = current && !isThisLCA;
            return Boolean.TRUE;
        } else {
            this.nLCAState = nThisState;
        }
        return Boolean.FALSE;
    } /* StateMachine.Exitable */
    public void DefaultEntryAction(
        BaseClass pObj,
        String pMsg
    ){
        // pHdStateMachine->lastEnteredState = pHdStateMachine->nCurrentState;
        this.lastEnteredState = this.nCurrentState;

        // pHdStateMachine->nDepth++;   // nDepth was not in Java skeleton, so omitted.
        System.out.println("Enter " + pMsg.substring(pMsg.lastIndexOf('\t')));
    } /* StateMachine.DefaultEntryAction */

    public void DefaultExitAction(
        BaseClass pObj,
        String pMsg
    ){
        System.out.println("Exit" + pMsg.substring(pMsg.lastIndexOf('\t')));
    } /* StateMachine.DefaultExitAction */

    public void DefaultDoingAction(
        BaseClass pObj,
        String pMsg
    ){

    } /* StateMachine.DefaultDoingAction */

    public Boolean IsIn(
        long nState
    ){
        long targetState = nState;


        return isIn(this.nCurrentState, targetState);
    } /* StateMachine.IsIn */

    public void Req(
        long entryPt
    ){
        this.nPseudostate = entryPt;

        // NOTE: C version forgot to return a bool; Java version is void, so this matches better.
    } /* StateMachine.Req */

    private static Boolean isIn(
        long leaf,
        long composite
    ){
        return (composite >= leaf) && ((composite & leaf) != 0);
    } /* StateMachine.isIn */
    public  StateMachine(
    ){
        pParentStm = null;
        nCurrentState = STATE_UNDEF;
        nLCAState = STATE_UNDEF;
        nTargetState = STATE_UNDEF;
        nSourceState = STATE_UNDEF;
        nPseudostate = STATE_UNDEF;
        bIsExternTrans = false;
        bHandled = false;
        wasHandled = false;
        lastEnteredState = STATE_UNDEF;
        pMain = null;
    }                                                                                           
    public StateMachine pParentStm;                               
    public long nCurrentState;                                  
    public long nLCAState;                                      
    public long nTargetState;                                   
    public long nSourceState;                                   
    public long nPseudostate;                                   
    public Boolean bIsExternTrans;                              
    public Boolean bHandled;                                    
    public Boolean wasHandled;                                  
    public long lastEnteredState;                               
    public BaseStmTop pMain;                                      
}
