/* File generated by Đức's ClasHStamP */
package all_notations.java_sample00.base;

import java.io.*;
import java.util.*;
import all_notations.java_sample00.abstracts.*;
import simulator.SimulatorManager;
import java.awt.Rectangle;

public  class StateMachine
{
    public static final long STATE_UNDEF = 0;                   
    public Boolean Enterable(
        long nThisState
    ){
        // BOOL isThisLCA = IS_IN( pHdStateMachine->nLCAState, nThisState );
        boolean isThisLCA = isIn(this.nLCAState, nThisState);

        // if( !isThisLCA || pHdStateMachine->nLCAState == STATE_UNDEF ){ return TRUE; }
        if (!isThisLCA || this.nLCAState == STATE_UNDEF) {
            return Boolean.TRUE;
        }
        return Boolean.FALSE;
    } /* StateMachine.Enterable */

    public Boolean Exitable(
        long nThisState
    ){
        // BOOL isThisLCA = IS_IN( pHdStateMachine->nSourceState, nThisState )
        //                   && IS_IN( pHdStateMachine->nTargetState, nThisState );
        boolean isThisLCA =
            isIn(this.nSourceState, nThisState) &&
            isIn(this.nTargetState, nThisState);

        // if( !isThisLCA || pHdStateMachine->bIsExternTrans ){ 
        //     pHdStateMachine->bIsExternTrans &= !isThisLCA;
        //     return TRUE;
        // } else { 
        //     pHdStateMachine->nLCAState = nThisState;
        // }
        // return FALSE;
        if (!isThisLCA || Boolean.TRUE.equals(this.bIsExternTrans)) {
            boolean current = Boolean.TRUE.equals(this.bIsExternTrans);
            this.bIsExternTrans = current && !isThisLCA;
            return Boolean.TRUE;
        } else {
            this.nLCAState = nThisState;
        }
        return Boolean.FALSE;
    } /* StateMachine.Exitable */
    public void DefaultEntryAction(
        BaseClass pObj,
        String pMsg
    ){
        // pHdStateMachine->lastEnteredState = pHdStateMachine->nCurrentState;
        this.lastEnteredState = this.nCurrentState;

        // pHdStateMachine->nDepth++;   // nDepth was not in Java skeleton, so omitted.
        System.out.println("Enter " + pMsg.substring(pMsg.lastIndexOf('\t')));
        try {
            // Message format: "...\tX\tY\tW\tH\t...\tStateName" or sometimes starts with diagram name
            String[] parts = pMsg.split("\t");
            String stateName = parts[parts.length - 1];
            int len = parts.length;
            int x = Integer.parseInt(parts[len-9]);
            int y = Integer.parseInt(parts[len-8]);
            int w = Integer.parseInt(parts[len-7]);
            int h = Integer.parseInt(parts[len-6]);
            // Determine diagram and instance using this.pMain (owner) when available
            String diagram = (this.pMain != null && this.pMain.dgrName != null && !this.pMain.dgrName.isEmpty()) ? this.pMain.dgrName : (parts.length>0 ? parts[0] : "State_Machine");
            String instance = (this.pMain != null && this.pMain.instanceName != null) ? this.pMain.instanceName : "";
            // Add rectangle to simulator
            SimulatorManager.getInstance().addRect(diagram, instance, stateName, new Rectangle(x,y,w,h));
        } catch (Exception e) {
            // best-effort only
        }
    } /* StateMachine.DefaultEntryAction */

    public void DefaultExitAction(
        BaseClass pObj,
        String pMsg
    ){
        System.out.println("Exit" + pMsg.substring(pMsg.lastIndexOf('\t')));
        try {
            String[] parts = pMsg.split("\t");
            String stateName = parts[parts.length - 1];
            String instance = (this.pMain != null && this.pMain.instanceName != null) ? this.pMain.instanceName : "";
            SimulatorManager.getInstance().removeRect(instance, stateName);
        } catch (Exception e) {
        }
    } /* StateMachine.DefaultExitAction */

    public void DefaultDoingAction(
        BaseClass pObj,
        String pMsg
    ){
        // show rectangle for a short duration (100ms)
        try {
            String[] parts = pMsg.split("\t");
            String stateName = parts[parts.length - 1];
            int len = parts.length;
            int x = Integer.parseInt(parts[len-9]);
            int y = Integer.parseInt(parts[len-8]);
            int w = Integer.parseInt(parts[len-7]);
            int h = Integer.parseInt(parts[len-6]);
            String instance = (this.pMain != null && this.pMain.instanceName != null) ? this.pMain.instanceName : "";
            String diagram = (this.pMain != null && this.pMain.dgrName != null && !this.pMain.dgrName.isEmpty()) ? this.pMain.dgrName : (parts.length>0 ? parts[0] : "State_Machine");
            SimulatorManager.getInstance().addRect(diagram, instance, stateName, new Rectangle(x,y,w,h));
            // schedule removal after 100ms
            new Thread(() -> {
                try { Thread.sleep(100); } catch (InterruptedException ignored) {}
                SimulatorManager.getInstance().removeRect(instance, stateName);
            }).start();
        } catch (Exception e) {
        }

    } /* StateMachine.DefaultDoingAction */

    public Boolean IsIn(
        long nState
    ){
        long targetState = nState;


        return isIn(this.nCurrentState, targetState);
    } /* StateMachine.IsIn */

    public void Req(
        long entryPt
    ){
        this.nPseudostate = entryPt;

        // NOTE: C version forgot to return a bool; Java version is void, so this matches better.
    } /* StateMachine.Req */
    
    private static Boolean isIn(
        long leaf,
        long composite
    ){
        return (composite >= leaf) && ((composite & leaf) != 0);
    } /* StateMachine.isIn */
    public  StateMachine(
    ){
        pParentStm = null;
        nCurrentState = STATE_UNDEF;
        nLCAState = STATE_UNDEF;
        nTargetState = STATE_UNDEF;
        nSourceState = STATE_UNDEF;
        nPseudostate = STATE_UNDEF;
        bIsExternTrans = false;
        bHandled = false;
        wasHandled = false;
        lastEnteredState = STATE_UNDEF;
        pMain = null;
    }                                                                                           
    public StateMachine pParentStm;                               
    public long nCurrentState;                                  
    public long nLCAState;                                      
    public long nTargetState;                                   
    public long nSourceState;                                   
    public long nPseudostate;                                   
    public Boolean bIsExternTrans;                              
    public Boolean bHandled;                                    
    public Boolean wasHandled;                                  
    public long lastEnteredState;                               
    public BaseStmTop pMain;                                      
}